// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: kvs/v1/kvs.proto

package kvsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChangeType int32

const (
	ChangeType_CHANGE_TYPE_UNSPECIFIED ChangeType = 0
	ChangeType_CHANGE_TYPE_ADDED       ChangeType = 1
	ChangeType_CHANGE_TYPE_MODIFIED    ChangeType = 2
	ChangeType_CHANGE_TYPE_DELETED     ChangeType = 3
)

// Enum value maps for ChangeType.
var (
	ChangeType_name = map[int32]string{
		0: "CHANGE_TYPE_UNSPECIFIED",
		1: "CHANGE_TYPE_ADDED",
		2: "CHANGE_TYPE_MODIFIED",
		3: "CHANGE_TYPE_DELETED",
	}
	ChangeType_value = map[string]int32{
		"CHANGE_TYPE_UNSPECIFIED": 0,
		"CHANGE_TYPE_ADDED":       1,
		"CHANGE_TYPE_MODIFIED":    2,
		"CHANGE_TYPE_DELETED":     3,
	}
)

func (x ChangeType) Enum() *ChangeType {
	p := new(ChangeType)
	*p = x
	return p
}

func (x ChangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_kvs_v1_kvs_proto_enumTypes[0].Descriptor()
}

func (ChangeType) Type() protoreflect.EnumType {
	return &file_kvs_v1_kvs_proto_enumTypes[0]
}

func (x ChangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChangeType.Descriptor instead.
func (ChangeType) EnumDescriptor() ([]byte, []int) {
	return file_kvs_v1_kvs_proto_rawDescGZIP(), []int{0}
}

type ReadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogicalPath   string                 `protobuf:"bytes,1,opt,name=logical_path,json=logicalPath,proto3" json:"logical_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileRequest) Reset() {
	*x = ReadFileRequest{}
	mi := &file_kvs_v1_kvs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileRequest) ProtoMessage() {}

func (x *ReadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_v1_kvs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileRequest.ProtoReflect.Descriptor instead.
func (*ReadFileRequest) Descriptor() ([]byte, []int) {
	return file_kvs_v1_kvs_proto_rawDescGZIP(), []int{0}
}

func (x *ReadFileRequest) GetLogicalPath() string {
	if x != nil {
		return x.LogicalPath
	}
	return ""
}

type ReadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Version       *FileVersion           `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileResponse) Reset() {
	*x = ReadFileResponse{}
	mi := &file_kvs_v1_kvs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileResponse) ProtoMessage() {}

func (x *ReadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_v1_kvs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileResponse.ProtoReflect.Descriptor instead.
func (*ReadFileResponse) Descriptor() ([]byte, []int) {
	return file_kvs_v1_kvs_proto_rawDescGZIP(), []int{1}
}

func (x *ReadFileResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ReadFileResponse) GetVersion() *FileVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

type ReadFileStreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ReadFileStreamResponse_Version
	//	*ReadFileStreamResponse_Chunk
	Payload       isReadFileStreamResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileStreamResponse) Reset() {
	*x = ReadFileStreamResponse{}
	mi := &file_kvs_v1_kvs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileStreamResponse) ProtoMessage() {}

func (x *ReadFileStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_v1_kvs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileStreamResponse.ProtoReflect.Descriptor instead.
func (*ReadFileStreamResponse) Descriptor() ([]byte, []int) {
	return file_kvs_v1_kvs_proto_rawDescGZIP(), []int{2}
}

func (x *ReadFileStreamResponse) GetPayload() isReadFileStreamResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ReadFileStreamResponse) GetVersion() *FileVersion {
	if x != nil {
		if x, ok := x.Payload.(*ReadFileStreamResponse_Version); ok {
			return x.Version
		}
	}
	return nil
}

func (x *ReadFileStreamResponse) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ReadFileStreamResponse_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isReadFileStreamResponse_Payload interface {
	isReadFileStreamResponse_Payload()
}

type ReadFileStreamResponse_Version struct {
	Version *FileVersion `protobuf:"bytes,1,opt,name=version,proto3,oneof"`
}

type ReadFileStreamResponse_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*ReadFileStreamResponse_Version) isReadFileStreamResponse_Payload() {}

func (*ReadFileStreamResponse_Chunk) isReadFileStreamResponse_Payload() {}

type StatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogicalPath   string                 `protobuf:"bytes,1,opt,name=logical_path,json=logicalPath,proto3" json:"logical_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	mi := &file_kvs_v1_kvs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_v1_kvs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_kvs_v1_kvs_proto_rawDescGZIP(), []int{3}
}

func (x *StatRequest) GetLogicalPath() string {
	if x != nil {
		return x.LogicalPath
	}
	return ""
}

type StatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *FileInfo              `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	mi := &file_kvs_v1_kvs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_v1_kvs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_kvs_v1_kvs_proto_rawDescGZIP(), []int{4}
}

func (x *StatResponse) GetInfo() *FileInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type ListDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogicalDir    string                 `protobuf:"bytes,1,opt,name=logical_dir,json=logicalDir,proto3" json:"logical_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirRequest) Reset() {
	*x = ListDirRequest{}
	mi := &file_kvs_v1_kvs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirRequest) ProtoMessage() {}

func (x *ListDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_v1_kvs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirRequest.ProtoReflect.Descriptor instead.
func (*ListDirRequest) Descriptor() ([]byte, []int) {
	return file_kvs_v1_kvs_proto_rawDescGZIP(), []int{5}
}

func (x *ListDirRequest) GetLogicalDir() string {
	if x != nil {
		return x.LogicalDir
	}
	return ""
}

type ListDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*DirEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirResponse) Reset() {
	*x = ListDirResponse{}
	mi := &file_kvs_v1_kvs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirResponse) ProtoMessage() {}

func (x *ListDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_v1_kvs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirResponse.ProtoReflect.Descriptor instead.
func (*ListDirResponse) Descriptor() ([]byte, []int) {
	return file_kvs_v1_kvs_proto_rawDescGZIP(), []int{6}
}

func (x *ListDirResponse) GetEntries() []*DirEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type UpsertFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Writes        []*PathWrite           `protobuf:"bytes,1,rep,name=writes,proto3" json:"writes,omitempty"`
	Context       *MutationContext       `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertFilesRequest) Reset() {
	*x = UpsertFilesRequest{}
	mi := &file_kvs_v1_kvs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertFilesRequest) ProtoMessage() {}

func (x *UpsertFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_v1_kvs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertFilesRequest.ProtoReflect.Descriptor instead.
func (*UpsertFilesRequest) Descriptor() ([]byte, []int) {
	return file_kvs_v1_kvs_proto_rawDescGZIP(), []int{7}
}

func (x *UpsertFilesRequest) GetWrites() []*PathWrite {
	if x != nil {
		return x.Writes
	}
	return nil
}

func (x *UpsertFilesRequest) GetContext() *MutationContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type DeletePathsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deletes       []*PathDelete          `protobuf:"bytes,1,rep,name=deletes,proto3" json:"deletes,omitempty"`
	Context       *MutationContext       `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePathsRequest) Reset() {
	*x = DeletePathsRequest{}
	mi := &file_kvs_v1_kvs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePathsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePathsRequest) ProtoMessage() {}

func (x *DeletePathsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_v1_kvs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePathsRequest.ProtoReflect.Descriptor instead.
func (*DeletePathsRequest) Descriptor() ([]byte, []int) {
	return file_kvs_v1_kvs_proto_rawDescGZIP(), []int{8}
}

func (x *DeletePathsRequest) GetDeletes() []*PathDelete {
	if x != nil {
		return x.Deletes
	}
	return nil
}

func (x *DeletePathsRequest) GetContext() *MutationContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type ListVersionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogicalPath   string                 `protobuf:"bytes,1,opt,name=logical_path,json=logicalPath,proto3" json:"logical_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVersionsRequest) Reset() {
	*x = ListVersionsRequest{}
	mi := &file_kvs_v1_kvs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVersionsRequest) ProtoMessage() {}

func (x *ListVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_v1_kvs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVersionsRequest.ProtoReflect.Descriptor instead.
func (*ListVersionsRequest) Descriptor() ([]byte, []int) {
	return file_kvs_v1_kvs_proto_rawDescGZIP(), []int{9}
}

func (x *ListVersionsRequest) GetLogicalPath() string {
	if x != nil {
		return x.LogicalPath
	}
	return ""
}

type ListVersionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []*FileVersion         `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVersionsResponse) Reset() {
	*x = ListVersionsResponse{}
	mi := &file_kvs_v1_kvs_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVersionsResponse) ProtoMessage() {}

func (x *ListVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_v1_kvs_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVersionsResponse.ProtoReflect.Descriptor instead.
func (*ListVersionsResponse) Descriptor() ([]byte, []int) {
	return file_kvs_v1_kvs_proto_rawDescGZIP(), []int{10}
}

func (x *ListVersionsResponse) GetVersions() []*FileVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

type GetVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogicalPath   string                 `protobuf:"bytes,1,opt,name=logical_path,json=logicalPath,proto3" json:"logical_path,omitempty"`
	VersionId     string                 `protobuf:"bytes,2,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionRequest) Reset() {
	*x = GetVersionRequest{}
	mi := &file_kvs_v1_kvs_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionRequest) ProtoMessage() {}

func (x *GetVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_v1_kvs_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionRequest.ProtoReflect.Descriptor instead.
func (*GetVersionRequest) Descriptor() ([]byte, []int) {
	return file_kvs_v1_kvs_proto_rawDescGZIP(), []int{11}
}

func (x *GetVersionRequest) GetLogicalPath() string {
	if x != nil {
		return x.LogicalPath
	}
	return ""
}

func (x *GetVersionRequest) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

type GetVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *VersionedFile         `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionResponse) Reset() {
	*x = GetVersionResponse{}
	mi := &file_kvs_v1_kvs_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionResponse) ProtoMessage() {}

func (x *GetVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_v1_kvs_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionResponse.ProtoReflect.Descriptor instead.
func (*GetVersionResponse) Descriptor() ([]byte, []int) {
	return file_kvs_v1_kvs_proto_rawDescGZIP(), []int{12}
}

func (x *GetVersionResponse) GetFile() *VersionedFile {
	if x != nil {
		return x.File
	}
	return nil
}

type PutFileMeta struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LogicalPath       string                 `protobuf:"bytes,1,opt,name=logical_path,json=logicalPath,proto3" json:"logical_path,omitempty"`
	ExpectedVersionId string                 `protobuf:"bytes,2,opt,name=expected_version_id,json=expectedVersionId,proto3" json:"expected_version_id,omitempty"`
	Context           *MutationContext       `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PutFileMeta) Reset() {
	*x = PutFileMeta{}
	mi := &file_kvs_v1_kvs_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutFileMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutFileMeta) ProtoMessage() {}

func (x *PutFileMeta) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_v1_kvs_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutFileMeta.ProtoReflect.Descriptor instead.
func (*PutFileMeta) Descriptor() ([]byte, []int) {
	return file_kvs_v1_kvs_proto_rawDescGZIP(), []int{13}
}

func (x *PutFileMeta) GetLogicalPath() string {
	if x != nil {
		return x.LogicalPath
	}
	return ""
}

func (x *PutFileMeta) GetExpectedVersionId() string {
	if x != nil {
		return x.ExpectedVersionId
	}
	return ""
}

func (x *PutFileMeta) GetContext() *MutationContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type PutFileStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*PutFileStreamRequest_Meta
	//	*PutFileStreamRequest_Chunk
	Payload       isPutFileStreamRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutFileStreamRequest) Reset() {
	*x = PutFileStreamRequest{}
	mi := &file_kvs_v1_kvs_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutFileStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutFileStreamRequest) ProtoMessage() {}

func (x *PutFileStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_v1_kvs_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutFileStreamRequest.ProtoReflect.Descriptor instead.
func (*PutFileStreamRequest) Descriptor() ([]byte, []int) {
	return file_kvs_v1_kvs_proto_rawDescGZIP(), []int{14}
}

func (x *PutFileStreamRequest) GetPayload() isPutFileStreamRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PutFileStreamRequest) GetMeta() *PutFileMeta {
	if x != nil {
		if x, ok := x.Payload.(*PutFileStreamRequest_Meta); ok {
			return x.Meta
		}
	}
	return nil
}

func (x *PutFileStreamRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Payload.(*PutFileStreamRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isPutFileStreamRequest_Payload interface {
	isPutFileStreamRequest_Payload()
}

type PutFileStreamRequest_Meta struct {
	Meta *PutFileMeta `protobuf:"bytes,1,opt,name=meta,proto3,oneof"`
}

type PutFileStreamRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*PutFileStreamRequest_Meta) isPutFileStreamRequest_Payload() {}

func (*PutFileStreamRequest_Chunk) isPutFileStreamRequest_Payload() {}

type PutFileStreamResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BatchRevisionId string                 `protobuf:"bytes,1,opt,name=batch_revision_id,json=batchRevisionId,proto3" json:"batch_revision_id,omitempty"`
	Version         *FileVersion           `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PutFileStreamResponse) Reset() {
	*x = PutFileStreamResponse{}
	mi := &file_kvs_v1_kvs_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutFileStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutFileStreamResponse) ProtoMessage() {}

func (x *PutFileStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_v1_kvs_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutFileStreamResponse.ProtoReflect.Descriptor instead.
func (*PutFileStreamResponse) Descriptor() ([]byte, []int) {
	return file_kvs_v1_kvs_proto_rawDescGZIP(), []int{15}
}

func (x *PutFileStreamResponse) GetBatchRevisionId() string {
	if x != nil {
		return x.BatchRevisionId
	}
	return ""
}

func (x *PutFileStreamResponse) GetVersion() *FileVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefixes      []string               `protobuf:"bytes,1,rep,name=prefixes,proto3" json:"prefixes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_kvs_v1_kvs_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_v1_kvs_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_kvs_v1_kvs_proto_rawDescGZIP(), []int{16}
}

func (x *WatchRequest) GetPrefixes() []string {
	if x != nil {
		return x.Prefixes
	}
	return nil
}

type WatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *ChangeEvent           `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchResponse) Reset() {
	*x = WatchResponse{}
	mi := &file_kvs_v1_kvs_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResponse) ProtoMessage() {}

func (x *WatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_v1_kvs_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResponse.ProtoReflect.Descriptor instead.
func (*WatchResponse) Descriptor() ([]byte, []int) {
	return file_kvs_v1_kvs_proto_rawDescGZIP(), []int{17}
}

func (x *WatchResponse) GetEvent() *ChangeEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type MutationContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrincipalId   string                 `protobuf:"bytes,1,opt,name=principal_id,json=principalId,proto3" json:"principal_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutationContext) Reset() {
	*x = MutationContext{}
	mi := &file_kvs_v1_kvs_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutationContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutationContext) ProtoMessage() {}

func (x *MutationContext) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_v1_kvs_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutationContext.ProtoReflect.Descriptor instead.
func (*MutationContext) Descriptor() ([]byte, []int) {
	return file_kvs_v1_kvs_proto_rawDescGZIP(), []int{18}
}

func (x *MutationContext) GetPrincipalId() string {
	if x != nil {
		return x.PrincipalId
	}
	return ""
}

func (x *MutationContext) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *MutationContext) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type PathWrite struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LogicalPath       string                 `protobuf:"bytes,1,opt,name=logical_path,json=logicalPath,proto3" json:"logical_path,omitempty"`
	Content           []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ExpectedVersionId string                 `protobuf:"bytes,3,opt,name=expected_version_id,json=expectedVersionId,proto3" json:"expected_version_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PathWrite) Reset() {
	*x = PathWrite{}
	mi := &file_kvs_v1_kvs_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathWrite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathWrite) ProtoMessage() {}

func (x *PathWrite) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_v1_kvs_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathWrite.ProtoReflect.Descriptor instead.
func (*PathWrite) Descriptor() ([]byte, []int) {
	return file_kvs_v1_kvs_proto_rawDescGZIP(), []int{19}
}

func (x *PathWrite) GetLogicalPath() string {
	if x != nil {
		return x.LogicalPath
	}
	return ""
}

func (x *PathWrite) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *PathWrite) GetExpectedVersionId() string {
	if x != nil {
		return x.ExpectedVersionId
	}
	return ""
}

type PathDelete struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LogicalPath       string                 `protobuf:"bytes,1,opt,name=logical_path,json=logicalPath,proto3" json:"logical_path,omitempty"`
	ExpectedVersionId string                 `protobuf:"bytes,2,opt,name=expected_version_id,json=expectedVersionId,proto3" json:"expected_version_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PathDelete) Reset() {
	*x = PathDelete{}
	mi := &file_kvs_v1_kvs_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathDelete) ProtoMessage() {}

func (x *PathDelete) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_v1_kvs_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathDelete.ProtoReflect.Descriptor instead.
func (*PathDelete) Descriptor() ([]byte, []int) {
	return file_kvs_v1_kvs_proto_rawDescGZIP(), []int{20}
}

func (x *PathDelete) GetLogicalPath() string {
	if x != nil {
		return x.LogicalPath
	}
	return ""
}

func (x *PathDelete) GetExpectedVersionId() string {
	if x != nil {
		return x.ExpectedVersionId
	}
	return ""
}

type BatchRevision struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BatchRevisionId string                 `protobuf:"bytes,1,opt,name=batch_revision_id,json=batchRevisionId,proto3" json:"batch_revision_id,omitempty"`
	Files           []*FileVersion         `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BatchRevision) Reset() {
	*x = BatchRevision{}
	mi := &file_kvs_v1_kvs_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRevision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRevision) ProtoMessage() {}

func (x *BatchRevision) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_v1_kvs_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRevision.ProtoReflect.Descriptor instead.
func (*BatchRevision) Descriptor() ([]byte, []int) {
	return file_kvs_v1_kvs_proto_rawDescGZIP(), []int{21}
}

func (x *BatchRevision) GetBatchRevisionId() string {
	if x != nil {
		return x.BatchRevisionId
	}
	return ""
}

func (x *BatchRevision) GetFiles() []*FileVersion {
	if x != nil {
		return x.Files
	}
	return nil
}

type FileVersion struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LogicalPath     string                 `protobuf:"bytes,1,opt,name=logical_path,json=logicalPath,proto3" json:"logical_path,omitempty"`
	VersionId       string                 `protobuf:"bytes,2,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	BatchRevisionId string                 `protobuf:"bytes,3,opt,name=batch_revision_id,json=batchRevisionId,proto3" json:"batch_revision_id,omitempty"`
	ContentSha256   string                 `protobuf:"bytes,4,opt,name=content_sha256,json=contentSha256,proto3" json:"content_sha256,omitempty"`
	CommittedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=committed_at,json=committedAt,proto3" json:"committed_at,omitempty"`
	Tombstone       bool                   `protobuf:"varint,6,opt,name=tombstone,proto3" json:"tombstone,omitempty"`
	PrincipalId     string                 `protobuf:"bytes,7,opt,name=principal_id,json=principalId,proto3" json:"principal_id,omitempty"`
	Reason          string                 `protobuf:"bytes,8,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FileVersion) Reset() {
	*x = FileVersion{}
	mi := &file_kvs_v1_kvs_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileVersion) ProtoMessage() {}

func (x *FileVersion) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_v1_kvs_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileVersion.ProtoReflect.Descriptor instead.
func (*FileVersion) Descriptor() ([]byte, []int) {
	return file_kvs_v1_kvs_proto_rawDescGZIP(), []int{22}
}

func (x *FileVersion) GetLogicalPath() string {
	if x != nil {
		return x.LogicalPath
	}
	return ""
}

func (x *FileVersion) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *FileVersion) GetBatchRevisionId() string {
	if x != nil {
		return x.BatchRevisionId
	}
	return ""
}

func (x *FileVersion) GetContentSha256() string {
	if x != nil {
		return x.ContentSha256
	}
	return ""
}

func (x *FileVersion) GetCommittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CommittedAt
	}
	return nil
}

func (x *FileVersion) GetTombstone() bool {
	if x != nil {
		return x.Tombstone
	}
	return false
}

func (x *FileVersion) GetPrincipalId() string {
	if x != nil {
		return x.PrincipalId
	}
	return ""
}

func (x *FileVersion) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type VersionedFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       *FileVersion           `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionedFile) Reset() {
	*x = VersionedFile{}
	mi := &file_kvs_v1_kvs_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionedFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionedFile) ProtoMessage() {}

func (x *VersionedFile) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_v1_kvs_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionedFile.ProtoReflect.Descriptor instead.
func (*VersionedFile) Descriptor() ([]byte, []int) {
	return file_kvs_v1_kvs_proto_rawDescGZIP(), []int{23}
}

func (x *VersionedFile) GetVersion() *FileVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *VersionedFile) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type DirEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsDir         bool                   `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirEntry) Reset() {
	*x = DirEntry{}
	mi := &file_kvs_v1_kvs_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirEntry) ProtoMessage() {}

func (x *DirEntry) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_v1_kvs_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirEntry.ProtoReflect.Descriptor instead.
func (*DirEntry) Descriptor() ([]byte, []int) {
	return file_kvs_v1_kvs_proto_rawDescGZIP(), []int{24}
}

func (x *DirEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DirEntry) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *DirEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	VersionId     string                 `protobuf:"bytes,3,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	ModTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_kvs_v1_kvs_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_v1_kvs_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_kvs_v1_kvs_proto_rawDescGZIP(), []int{25}
}

func (x *FileInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *FileInfo) GetModTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ModTime
	}
	return nil
}

type ChangeEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LogicalPath     string                 `protobuf:"bytes,1,opt,name=logical_path,json=logicalPath,proto3" json:"logical_path,omitempty"`
	Type            ChangeType             `protobuf:"varint,2,opt,name=type,proto3,enum=kvs.v1.ChangeType" json:"type,omitempty"`
	VersionId       string                 `protobuf:"bytes,3,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	BatchRevisionId string                 `protobuf:"bytes,4,opt,name=batch_revision_id,json=batchRevisionId,proto3" json:"batch_revision_id,omitempty"`
	CommittedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=committed_at,json=committedAt,proto3" json:"committed_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChangeEvent) Reset() {
	*x = ChangeEvent{}
	mi := &file_kvs_v1_kvs_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeEvent) ProtoMessage() {}

func (x *ChangeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_kvs_v1_kvs_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeEvent.ProtoReflect.Descriptor instead.
func (*ChangeEvent) Descriptor() ([]byte, []int) {
	return file_kvs_v1_kvs_proto_rawDescGZIP(), []int{26}
}

func (x *ChangeEvent) GetLogicalPath() string {
	if x != nil {
		return x.LogicalPath
	}
	return ""
}

func (x *ChangeEvent) GetType() ChangeType {
	if x != nil {
		return x.Type
	}
	return ChangeType_CHANGE_TYPE_UNSPECIFIED
}

func (x *ChangeEvent) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *ChangeEvent) GetBatchRevisionId() string {
	if x != nil {
		return x.BatchRevisionId
	}
	return ""
}

func (x *ChangeEvent) GetCommittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CommittedAt
	}
	return nil
}

var File_kvs_v1_kvs_proto protoreflect.FileDescriptor

const file_kvs_v1_kvs_proto_rawDesc = "" +
	"\n" +
	"\x10kvs/v1/kvs.proto\x12\x06kvs.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"4\n" +
	"\x0fReadFileRequest\x12!\n" +
	"\flogical_path\x18\x01 \x01(\tR\vlogicalPath\"[\n" +
	"\x10ReadFileResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\x12-\n" +
	"\aversion\x18\x02 \x01(\v2\x13.kvs.v1.FileVersionR\aversion\"l\n" +
	"\x16ReadFileStreamResponse\x12/\n" +
	"\aversion\x18\x01 \x01(\v2\x13.kvs.v1.FileVersionH\x00R\aversion\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\t\n" +
	"\apayload\"0\n" +
	"\vStatRequest\x12!\n" +
	"\flogical_path\x18\x01 \x01(\tR\vlogicalPath\"4\n" +
	"\fStatResponse\x12$\n" +
	"\x04info\x18\x01 \x01(\v2\x10.kvs.v1.FileInfoR\x04info\"1\n" +
	"\x0eListDirRequest\x12\x1f\n" +
	"\vlogical_dir\x18\x01 \x01(\tR\n" +
	"logicalDir\"=\n" +
	"\x0fListDirResponse\x12*\n" +
	"\aentries\x18\x01 \x03(\v2\x10.kvs.v1.DirEntryR\aentries\"r\n" +
	"\x12UpsertFilesRequest\x12)\n" +
	"\x06writes\x18\x01 \x03(\v2\x11.kvs.v1.PathWriteR\x06writes\x121\n" +
	"\acontext\x18\x02 \x01(\v2\x17.kvs.v1.MutationContextR\acontext\"u\n" +
	"\x12DeletePathsRequest\x12,\n" +
	"\adeletes\x18\x01 \x03(\v2\x12.kvs.v1.PathDeleteR\adeletes\x121\n" +
	"\acontext\x18\x02 \x01(\v2\x17.kvs.v1.MutationContextR\acontext\"8\n" +
	"\x13ListVersionsRequest\x12!\n" +
	"\flogical_path\x18\x01 \x01(\tR\vlogicalPath\"G\n" +
	"\x14ListVersionsResponse\x12/\n" +
	"\bversions\x18\x01 \x03(\v2\x13.kvs.v1.FileVersionR\bversions\"U\n" +
	"\x11GetVersionRequest\x12!\n" +
	"\flogical_path\x18\x01 \x01(\tR\vlogicalPath\x12\x1d\n" +
	"\n" +
	"version_id\x18\x02 \x01(\tR\tversionId\"?\n" +
	"\x12GetVersionResponse\x12)\n" +
	"\x04file\x18\x01 \x01(\v2\x15.kvs.v1.VersionedFileR\x04file\"\x93\x01\n" +
	"\vPutFileMeta\x12!\n" +
	"\flogical_path\x18\x01 \x01(\tR\vlogicalPath\x12.\n" +
	"\x13expected_version_id\x18\x02 \x01(\tR\x11expectedVersionId\x121\n" +
	"\acontext\x18\x03 \x01(\v2\x17.kvs.v1.MutationContextR\acontext\"d\n" +
	"\x14PutFileStreamRequest\x12)\n" +
	"\x04meta\x18\x01 \x01(\v2\x13.kvs.v1.PutFileMetaH\x00R\x04meta\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\t\n" +
	"\apayload\"r\n" +
	"\x15PutFileStreamResponse\x12*\n" +
	"\x11batch_revision_id\x18\x01 \x01(\tR\x0fbatchRevisionId\x12-\n" +
	"\aversion\x18\x02 \x01(\v2\x13.kvs.v1.FileVersionR\aversion\"*\n" +
	"\fWatchRequest\x12\x1a\n" +
	"\bprefixes\x18\x01 \x03(\tR\bprefixes\":\n" +
	"\rWatchResponse\x12)\n" +
	"\x05event\x18\x01 \x01(\v2\x13.kvs.v1.ChangeEventR\x05event\"s\n" +
	"\x0fMutationContext\x12!\n" +
	"\fprincipal_id\x18\x01 \x01(\tR\vprincipalId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12%\n" +
	"\x0ecorrelation_id\x18\x03 \x01(\tR\rcorrelationId\"x\n" +
	"\tPathWrite\x12!\n" +
	"\flogical_path\x18\x01 \x01(\tR\vlogicalPath\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12.\n" +
	"\x13expected_version_id\x18\x03 \x01(\tR\x11expectedVersionId\"_\n" +
	"\n" +
	"PathDelete\x12!\n" +
	"\flogical_path\x18\x01 \x01(\tR\vlogicalPath\x12.\n" +
	"\x13expected_version_id\x18\x02 \x01(\tR\x11expectedVersionId\"f\n" +
	"\rBatchRevision\x12*\n" +
	"\x11batch_revision_id\x18\x01 \x01(\tR\x0fbatchRevisionId\x12)\n" +
	"\x05files\x18\x02 \x03(\v2\x13.kvs.v1.FileVersionR\x05files\"\xba\x02\n" +
	"\vFileVersion\x12!\n" +
	"\flogical_path\x18\x01 \x01(\tR\vlogicalPath\x12\x1d\n" +
	"\n" +
	"version_id\x18\x02 \x01(\tR\tversionId\x12*\n" +
	"\x11batch_revision_id\x18\x03 \x01(\tR\x0fbatchRevisionId\x12%\n" +
	"\x0econtent_sha256\x18\x04 \x01(\tR\rcontentSha256\x12=\n" +
	"\fcommitted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vcommittedAt\x12\x1c\n" +
	"\ttombstone\x18\x06 \x01(\bR\ttombstone\x12!\n" +
	"\fprincipal_id\x18\a \x01(\tR\vprincipalId\x12\x16\n" +
	"\x06reason\x18\b \x01(\tR\x06reason\"X\n" +
	"\rVersionedFile\x12-\n" +
	"\aversion\x18\x01 \x01(\v2\x13.kvs.v1.FileVersionR\aversion\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"I\n" +
	"\bDirEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x15\n" +
	"\x06is_dir\x18\x02 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"\x88\x01\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x1d\n" +
	"\n" +
	"version_id\x18\x03 \x01(\tR\tversionId\x125\n" +
	"\bmod_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\amodTime\"\xe2\x01\n" +
	"\vChangeEvent\x12!\n" +
	"\flogical_path\x18\x01 \x01(\tR\vlogicalPath\x12&\n" +
	"\x04type\x18\x02 \x01(\x0e2\x12.kvs.v1.ChangeTypeR\x04type\x12\x1d\n" +
	"\n" +
	"version_id\x18\x03 \x01(\tR\tversionId\x12*\n" +
	"\x11batch_revision_id\x18\x04 \x01(\tR\x0fbatchRevisionId\x12=\n" +
	"\fcommitted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vcommittedAt*s\n" +
	"\n" +
	"ChangeType\x12\x1b\n" +
	"\x17CHANGE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11CHANGE_TYPE_ADDED\x10\x01\x12\x18\n" +
	"\x14CHANGE_TYPE_MODIFIED\x10\x02\x12\x17\n" +
	"\x13CHANGE_TYPE_DELETED\x10\x032\xf1\x05\n" +
	"\aKVStore\x12=\n" +
	"\bReadFile\x12\x17.kvs.v1.ReadFileRequest\x1a\x18.kvs.v1.ReadFileResponse\x12K\n" +
	"\x0eReadFileStream\x12\x17.kvs.v1.ReadFileRequest\x1a\x1e.kvs.v1.ReadFileStreamResponse0\x01\x121\n" +
	"\x04Stat\x12\x13.kvs.v1.StatRequest\x1a\x14.kvs.v1.StatResponse\x12:\n" +
	"\aListDir\x12\x16.kvs.v1.ListDirRequest\x1a\x17.kvs.v1.ListDirResponse\x12@\n" +
	"\vUpsertFiles\x12\x1a.kvs.v1.UpsertFilesRequest\x1a\x15.kvs.v1.BatchRevision\x12@\n" +
	"\vDeletePaths\x12\x1a.kvs.v1.DeletePathsRequest\x1a\x15.kvs.v1.BatchRevision\x12I\n" +
	"\fListVersions\x12\x1b.kvs.v1.ListVersionsRequest\x1a\x1c.kvs.v1.ListVersionsResponse\x12C\n" +
	"\n" +
	"GetVersion\x12\x19.kvs.v1.GetVersionRequest\x1a\x1a.kvs.v1.GetVersionResponse\x12O\n" +
	"\x10GetVersionStream\x12\x19.kvs.v1.GetVersionRequest\x1a\x1e.kvs.v1.ReadFileStreamResponse0\x01\x12N\n" +
	"\rPutFileStream\x12\x1c.kvs.v1.PutFileStreamRequest\x1a\x1d.kvs.v1.PutFileStreamResponse(\x01\x126\n" +
	"\x05Watch\x12\x14.kvs.v1.WatchRequest\x1a\x15.kvs.v1.WatchResponse0\x01B4Z2github.com/rydzu/ainfra/kvs/api/proto/kvs/v1;kvsv1b\x06proto3"

var (
	file_kvs_v1_kvs_proto_rawDescOnce sync.Once
	file_kvs_v1_kvs_proto_rawDescData []byte
)

func file_kvs_v1_kvs_proto_rawDescGZIP() []byte {
	file_kvs_v1_kvs_proto_rawDescOnce.Do(func() {
		file_kvs_v1_kvs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kvs_v1_kvs_proto_rawDesc), len(file_kvs_v1_kvs_proto_rawDesc)))
	})
	return file_kvs_v1_kvs_proto_rawDescData
}

var file_kvs_v1_kvs_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kvs_v1_kvs_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_kvs_v1_kvs_proto_goTypes = []any{
	(ChangeType)(0),                // 0: kvs.v1.ChangeType
	(*ReadFileRequest)(nil),        // 1: kvs.v1.ReadFileRequest
	(*ReadFileResponse)(nil),       // 2: kvs.v1.ReadFileResponse
	(*ReadFileStreamResponse)(nil), // 3: kvs.v1.ReadFileStreamResponse
	(*StatRequest)(nil),            // 4: kvs.v1.StatRequest
	(*StatResponse)(nil),           // 5: kvs.v1.StatResponse
	(*ListDirRequest)(nil),         // 6: kvs.v1.ListDirRequest
	(*ListDirResponse)(nil),        // 7: kvs.v1.ListDirResponse
	(*UpsertFilesRequest)(nil),     // 8: kvs.v1.UpsertFilesRequest
	(*DeletePathsRequest)(nil),     // 9: kvs.v1.DeletePathsRequest
	(*ListVersionsRequest)(nil),    // 10: kvs.v1.ListVersionsRequest
	(*ListVersionsResponse)(nil),   // 11: kvs.v1.ListVersionsResponse
	(*GetVersionRequest)(nil),      // 12: kvs.v1.GetVersionRequest
	(*GetVersionResponse)(nil),     // 13: kvs.v1.GetVersionResponse
	(*PutFileMeta)(nil),            // 14: kvs.v1.PutFileMeta
	(*PutFileStreamRequest)(nil),   // 15: kvs.v1.PutFileStreamRequest
	(*PutFileStreamResponse)(nil),  // 16: kvs.v1.PutFileStreamResponse
	(*WatchRequest)(nil),           // 17: kvs.v1.WatchRequest
	(*WatchResponse)(nil),          // 18: kvs.v1.WatchResponse
	(*MutationContext)(nil),        // 19: kvs.v1.MutationContext
	(*PathWrite)(nil),              // 20: kvs.v1.PathWrite
	(*PathDelete)(nil),             // 21: kvs.v1.PathDelete
	(*BatchRevision)(nil),          // 22: kvs.v1.BatchRevision
	(*FileVersion)(nil),            // 23: kvs.v1.FileVersion
	(*VersionedFile)(nil),          // 24: kvs.v1.VersionedFile
	(*DirEntry)(nil),               // 25: kvs.v1.DirEntry
	(*FileInfo)(nil),               // 26: kvs.v1.FileInfo
	(*ChangeEvent)(nil),            // 27: kvs.v1.ChangeEvent
	(*timestamppb.Timestamp)(nil),  // 28: google.protobuf.Timestamp
}
var file_kvs_v1_kvs_proto_depIdxs = []int32{
	23, // 0: kvs.v1.ReadFileResponse.version:type_name -> kvs.v1.FileVersion
	23, // 1: kvs.v1.ReadFileStreamResponse.version:type_name -> kvs.v1.FileVersion
	26, // 2: kvs.v1.StatResponse.info:type_name -> kvs.v1.FileInfo
	25, // 3: kvs.v1.ListDirResponse.entries:type_name -> kvs.v1.DirEntry
	20, // 4: kvs.v1.UpsertFilesRequest.writes:type_name -> kvs.v1.PathWrite
	19, // 5: kvs.v1.UpsertFilesRequest.context:type_name -> kvs.v1.MutationContext
	21, // 6: kvs.v1.DeletePathsRequest.deletes:type_name -> kvs.v1.PathDelete
	19, // 7: kvs.v1.DeletePathsRequest.context:type_name -> kvs.v1.MutationContext
	23, // 8: kvs.v1.ListVersionsResponse.versions:type_name -> kvs.v1.FileVersion
	24, // 9: kvs.v1.GetVersionResponse.file:type_name -> kvs.v1.VersionedFile
	19, // 10: kvs.v1.PutFileMeta.context:type_name -> kvs.v1.MutationContext
	14, // 11: kvs.v1.PutFileStreamRequest.meta:type_name -> kvs.v1.PutFileMeta
	23, // 12: kvs.v1.PutFileStreamResponse.version:type_name -> kvs.v1.FileVersion
	27, // 13: kvs.v1.WatchResponse.event:type_name -> kvs.v1.ChangeEvent
	23, // 14: kvs.v1.BatchRevision.files:type_name -> kvs.v1.FileVersion
	28, // 15: kvs.v1.FileVersion.committed_at:type_name -> google.protobuf.Timestamp
	23, // 16: kvs.v1.VersionedFile.version:type_name -> kvs.v1.FileVersion
	28, // 17: kvs.v1.FileInfo.mod_time:type_name -> google.protobuf.Timestamp
	0,  // 18: kvs.v1.ChangeEvent.type:type_name -> kvs.v1.ChangeType
	28, // 19: kvs.v1.ChangeEvent.committed_at:type_name -> google.protobuf.Timestamp
	1,  // 20: kvs.v1.KVStore.ReadFile:input_type -> kvs.v1.ReadFileRequest
	1,  // 21: kvs.v1.KVStore.ReadFileStream:input_type -> kvs.v1.ReadFileRequest
	4,  // 22: kvs.v1.KVStore.Stat:input_type -> kvs.v1.StatRequest
	6,  // 23: kvs.v1.KVStore.ListDir:input_type -> kvs.v1.ListDirRequest
	8,  // 24: kvs.v1.KVStore.UpsertFiles:input_type -> kvs.v1.UpsertFilesRequest
	9,  // 25: kvs.v1.KVStore.DeletePaths:input_type -> kvs.v1.DeletePathsRequest
	10, // 26: kvs.v1.KVStore.ListVersions:input_type -> kvs.v1.ListVersionsRequest
	12, // 27: kvs.v1.KVStore.GetVersion:input_type -> kvs.v1.GetVersionRequest
	12, // 28: kvs.v1.KVStore.GetVersionStream:input_type -> kvs.v1.GetVersionRequest
	15, // 29: kvs.v1.KVStore.PutFileStream:input_type -> kvs.v1.PutFileStreamRequest
	17, // 30: kvs.v1.KVStore.Watch:input_type -> kvs.v1.WatchRequest
	2,  // 31: kvs.v1.KVStore.ReadFile:output_type -> kvs.v1.ReadFileResponse
	3,  // 32: kvs.v1.KVStore.ReadFileStream:output_type -> kvs.v1.ReadFileStreamResponse
	5,  // 33: kvs.v1.KVStore.Stat:output_type -> kvs.v1.StatResponse
	7,  // 34: kvs.v1.KVStore.ListDir:output_type -> kvs.v1.ListDirResponse
	22, // 35: kvs.v1.KVStore.UpsertFiles:output_type -> kvs.v1.BatchRevision
	22, // 36: kvs.v1.KVStore.DeletePaths:output_type -> kvs.v1.BatchRevision
	11, // 37: kvs.v1.KVStore.ListVersions:output_type -> kvs.v1.ListVersionsResponse
	13, // 38: kvs.v1.KVStore.GetVersion:output_type -> kvs.v1.GetVersionResponse
	3,  // 39: kvs.v1.KVStore.GetVersionStream:output_type -> kvs.v1.ReadFileStreamResponse
	16, // 40: kvs.v1.KVStore.PutFileStream:output_type -> kvs.v1.PutFileStreamResponse
	18, // 41: kvs.v1.KVStore.Watch:output_type -> kvs.v1.WatchResponse
	31, // [31:42] is the sub-list for method output_type
	20, // [20:31] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_kvs_v1_kvs_proto_init() }
func file_kvs_v1_kvs_proto_init() {
	if File_kvs_v1_kvs_proto != nil {
		return
	}
	file_kvs_v1_kvs_proto_msgTypes[2].OneofWrappers = []any{
		(*ReadFileStreamResponse_Version)(nil),
		(*ReadFileStreamResponse_Chunk)(nil),
	}
	file_kvs_v1_kvs_proto_msgTypes[14].OneofWrappers = []any{
		(*PutFileStreamRequest_Meta)(nil),
		(*PutFileStreamRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kvs_v1_kvs_proto_rawDesc), len(file_kvs_v1_kvs_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kvs_v1_kvs_proto_goTypes,
		DependencyIndexes: file_kvs_v1_kvs_proto_depIdxs,
		EnumInfos:         file_kvs_v1_kvs_proto_enumTypes,
		MessageInfos:      file_kvs_v1_kvs_proto_msgTypes,
	}.Build()
	File_kvs_v1_kvs_proto = out.File
	file_kvs_v1_kvs_proto_goTypes = nil
	file_kvs_v1_kvs_proto_depIdxs = nil
}
