// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.31.1
// source: kvs/v1/kvs.proto

package kvsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KVStore_ReadFile_FullMethodName         = "/kvs.v1.KVStore/ReadFile"
	KVStore_ReadFileStream_FullMethodName   = "/kvs.v1.KVStore/ReadFileStream"
	KVStore_Stat_FullMethodName             = "/kvs.v1.KVStore/Stat"
	KVStore_ListDir_FullMethodName          = "/kvs.v1.KVStore/ListDir"
	KVStore_UpsertFiles_FullMethodName      = "/kvs.v1.KVStore/UpsertFiles"
	KVStore_DeletePaths_FullMethodName      = "/kvs.v1.KVStore/DeletePaths"
	KVStore_ListVersions_FullMethodName     = "/kvs.v1.KVStore/ListVersions"
	KVStore_GetVersion_FullMethodName       = "/kvs.v1.KVStore/GetVersion"
	KVStore_GetVersionStream_FullMethodName = "/kvs.v1.KVStore/GetVersionStream"
	KVStore_PutFileStream_FullMethodName    = "/kvs.v1.KVStore/PutFileStream"
	KVStore_Watch_FullMethodName            = "/kvs.v1.KVStore/Watch"
)

// KVStoreClient is the client API for KVStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KVStoreClient interface {
	ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error)
	ReadFileStream(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadFileStreamResponse], error)
	Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error)
	ListDir(ctx context.Context, in *ListDirRequest, opts ...grpc.CallOption) (*ListDirResponse, error)
	UpsertFiles(ctx context.Context, in *UpsertFilesRequest, opts ...grpc.CallOption) (*BatchRevision, error)
	DeletePaths(ctx context.Context, in *DeletePathsRequest, opts ...grpc.CallOption) (*BatchRevision, error)
	ListVersions(ctx context.Context, in *ListVersionsRequest, opts ...grpc.CallOption) (*ListVersionsResponse, error)
	GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error)
	GetVersionStream(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadFileStreamResponse], error)
	PutFileStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PutFileStreamRequest, PutFileStreamResponse], error)
	Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchResponse], error)
}

type kVStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewKVStoreClient(cc grpc.ClientConnInterface) KVStoreClient {
	return &kVStoreClient{cc}
}

func (c *kVStoreClient) ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadFileResponse)
	err := c.cc.Invoke(ctx, KVStore_ReadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVStoreClient) ReadFileStream(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadFileStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KVStore_ServiceDesc.Streams[0], KVStore_ReadFileStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReadFileRequest, ReadFileStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KVStore_ReadFileStreamClient = grpc.ServerStreamingClient[ReadFileStreamResponse]

func (c *kVStoreClient) Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatResponse)
	err := c.cc.Invoke(ctx, KVStore_Stat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVStoreClient) ListDir(ctx context.Context, in *ListDirRequest, opts ...grpc.CallOption) (*ListDirResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDirResponse)
	err := c.cc.Invoke(ctx, KVStore_ListDir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVStoreClient) UpsertFiles(ctx context.Context, in *UpsertFilesRequest, opts ...grpc.CallOption) (*BatchRevision, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchRevision)
	err := c.cc.Invoke(ctx, KVStore_UpsertFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVStoreClient) DeletePaths(ctx context.Context, in *DeletePathsRequest, opts ...grpc.CallOption) (*BatchRevision, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchRevision)
	err := c.cc.Invoke(ctx, KVStore_DeletePaths_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVStoreClient) ListVersions(ctx context.Context, in *ListVersionsRequest, opts ...grpc.CallOption) (*ListVersionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVersionsResponse)
	err := c.cc.Invoke(ctx, KVStore_ListVersions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVStoreClient) GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVersionResponse)
	err := c.cc.Invoke(ctx, KVStore_GetVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVStoreClient) GetVersionStream(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadFileStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KVStore_ServiceDesc.Streams[1], KVStore_GetVersionStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetVersionRequest, ReadFileStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KVStore_GetVersionStreamClient = grpc.ServerStreamingClient[ReadFileStreamResponse]

func (c *kVStoreClient) PutFileStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PutFileStreamRequest, PutFileStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KVStore_ServiceDesc.Streams[2], KVStore_PutFileStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PutFileStreamRequest, PutFileStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KVStore_PutFileStreamClient = grpc.ClientStreamingClient[PutFileStreamRequest, PutFileStreamResponse]

func (c *kVStoreClient) Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KVStore_ServiceDesc.Streams[3], KVStore_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, WatchResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KVStore_WatchClient = grpc.ServerStreamingClient[WatchResponse]

// KVStoreServer is the server API for KVStore service.
// All implementations must embed UnimplementedKVStoreServer
// for forward compatibility.
type KVStoreServer interface {
	ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error)
	ReadFileStream(*ReadFileRequest, grpc.ServerStreamingServer[ReadFileStreamResponse]) error
	Stat(context.Context, *StatRequest) (*StatResponse, error)
	ListDir(context.Context, *ListDirRequest) (*ListDirResponse, error)
	UpsertFiles(context.Context, *UpsertFilesRequest) (*BatchRevision, error)
	DeletePaths(context.Context, *DeletePathsRequest) (*BatchRevision, error)
	ListVersions(context.Context, *ListVersionsRequest) (*ListVersionsResponse, error)
	GetVersion(context.Context, *GetVersionRequest) (*GetVersionResponse, error)
	GetVersionStream(*GetVersionRequest, grpc.ServerStreamingServer[ReadFileStreamResponse]) error
	PutFileStream(grpc.ClientStreamingServer[PutFileStreamRequest, PutFileStreamResponse]) error
	Watch(*WatchRequest, grpc.ServerStreamingServer[WatchResponse]) error
	mustEmbedUnimplementedKVStoreServer()
}

// UnimplementedKVStoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKVStoreServer struct{}

func (UnimplementedKVStoreServer) ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadFile not implemented")
}
func (UnimplementedKVStoreServer) ReadFileStream(*ReadFileRequest, grpc.ServerStreamingServer[ReadFileStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method ReadFileStream not implemented")
}
func (UnimplementedKVStoreServer) Stat(context.Context, *StatRequest) (*StatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stat not implemented")
}
func (UnimplementedKVStoreServer) ListDir(context.Context, *ListDirRequest) (*ListDirResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDir not implemented")
}
func (UnimplementedKVStoreServer) UpsertFiles(context.Context, *UpsertFilesRequest) (*BatchRevision, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertFiles not implemented")
}
func (UnimplementedKVStoreServer) DeletePaths(context.Context, *DeletePathsRequest) (*BatchRevision, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePaths not implemented")
}
func (UnimplementedKVStoreServer) ListVersions(context.Context, *ListVersionsRequest) (*ListVersionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVersions not implemented")
}
func (UnimplementedKVStoreServer) GetVersion(context.Context, *GetVersionRequest) (*GetVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVersion not implemented")
}
func (UnimplementedKVStoreServer) GetVersionStream(*GetVersionRequest, grpc.ServerStreamingServer[ReadFileStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method GetVersionStream not implemented")
}
func (UnimplementedKVStoreServer) PutFileStream(grpc.ClientStreamingServer[PutFileStreamRequest, PutFileStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method PutFileStream not implemented")
}
func (UnimplementedKVStoreServer) Watch(*WatchRequest, grpc.ServerStreamingServer[WatchResponse]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedKVStoreServer) mustEmbedUnimplementedKVStoreServer() {}
func (UnimplementedKVStoreServer) testEmbeddedByValue()                 {}

// UnsafeKVStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KVStoreServer will
// result in compilation errors.
type UnsafeKVStoreServer interface {
	mustEmbedUnimplementedKVStoreServer()
}

func RegisterKVStoreServer(s grpc.ServiceRegistrar, srv KVStoreServer) {
	// If the following call panics, it indicates UnimplementedKVStoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KVStore_ServiceDesc, srv)
}

func _KVStore_ReadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVStoreServer).ReadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KVStore_ReadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVStoreServer).ReadFile(ctx, req.(*ReadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVStore_ReadFileStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KVStoreServer).ReadFileStream(m, &grpc.GenericServerStream[ReadFileRequest, ReadFileStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KVStore_ReadFileStreamServer = grpc.ServerStreamingServer[ReadFileStreamResponse]

func _KVStore_Stat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVStoreServer).Stat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KVStore_Stat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVStoreServer).Stat(ctx, req.(*StatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVStore_ListDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVStoreServer).ListDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KVStore_ListDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVStoreServer).ListDir(ctx, req.(*ListDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVStore_UpsertFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVStoreServer).UpsertFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KVStore_UpsertFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVStoreServer).UpsertFiles(ctx, req.(*UpsertFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVStore_DeletePaths_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePathsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVStoreServer).DeletePaths(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KVStore_DeletePaths_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVStoreServer).DeletePaths(ctx, req.(*DeletePathsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVStore_ListVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVersionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVStoreServer).ListVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KVStore_ListVersions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVStoreServer).ListVersions(ctx, req.(*ListVersionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVStore_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVStoreServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KVStore_GetVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVStoreServer).GetVersion(ctx, req.(*GetVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVStore_GetVersionStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetVersionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KVStoreServer).GetVersionStream(m, &grpc.GenericServerStream[GetVersionRequest, ReadFileStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KVStore_GetVersionStreamServer = grpc.ServerStreamingServer[ReadFileStreamResponse]

func _KVStore_PutFileStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(KVStoreServer).PutFileStream(&grpc.GenericServerStream[PutFileStreamRequest, PutFileStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KVStore_PutFileStreamServer = grpc.ClientStreamingServer[PutFileStreamRequest, PutFileStreamResponse]

func _KVStore_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KVStoreServer).Watch(m, &grpc.GenericServerStream[WatchRequest, WatchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KVStore_WatchServer = grpc.ServerStreamingServer[WatchResponse]

// KVStore_ServiceDesc is the grpc.ServiceDesc for KVStore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KVStore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kvs.v1.KVStore",
	HandlerType: (*KVStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadFile",
			Handler:    _KVStore_ReadFile_Handler,
		},
		{
			MethodName: "Stat",
			Handler:    _KVStore_Stat_Handler,
		},
		{
			MethodName: "ListDir",
			Handler:    _KVStore_ListDir_Handler,
		},
		{
			MethodName: "UpsertFiles",
			Handler:    _KVStore_UpsertFiles_Handler,
		},
		{
			MethodName: "DeletePaths",
			Handler:    _KVStore_DeletePaths_Handler,
		},
		{
			MethodName: "ListVersions",
			Handler:    _KVStore_ListVersions_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _KVStore_GetVersion_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReadFileStream",
			Handler:       _KVStore_ReadFileStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetVersionStream",
			Handler:       _KVStore_GetVersionStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PutFileStream",
			Handler:       _KVStore_PutFileStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Watch",
			Handler:       _KVStore_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "kvs/v1/kvs.proto",
}
