apiVersion: guardian/v1alpha1
kind: Intent
metadata:
    name: images
spec:
    intentType: standard
    targetPusher: k8s-main
    target:
        cluster: k8s-main
        namespace: agent
    locked: false
    assets:
        - type: ImageBuild
          name: lagent-llm-build
          version: 20260617-0821
          properties:
            imageTar: /partitions/agent/payloads/images/lagent-llm.tar
            registry: registry.strata.local:5000
            repository: lagent-llm
            sourceImage: lagent-llm:latest
        - type: ImageBuild
          name: lagent-backend-build
          version: 20260617-0821
          properties:
            imageTar: /partitions/agent/payloads/images/lagent-backend.tar
            registry: registry.strata.local:5000
            repository: lagent-backend
            sourceImage: lagent-backend:latest
        - type: ImageBuild
          name: lagent-frontend-build
          version: 20260617-0821
          properties:
            imageTar: /partitions/agent/payloads/images/lagent-frontend.tar
            registry: registry.strata.local:5000
            repository: lagent-frontend
            sourceImage: lagent-frontend:latest
