apiVersion: guardian/v1alpha1
kind: Intent
metadata:
    name: query
spec:
    intentType: standard
    joins:
        - ingest
    targetPusher: k8s-main
    target:
        cluster: k8s-main
        namespace: doctor
    locked: false
    assets:
        - type: Compute
          name: query
          version: 20260515-1449
          payload:
            k8s: /partitions/doctor/payloads/query.k8s.yaml
          properties:
            env:
                DOCTOR_DEFAULT_PARTITION: doctor
                DOCTOR_DEFAULT_TENANT: default
                DOCTOR_GUARDIAN_API_URL: http://guardian-ui.guardian-configs.svc.cluster.local:8090
                DOCTOR_GUARDIAN_UI_URL: http://127.0.0.1:8090
                DOCTOR_MONOFS_LOGENGINE_ADDR: monofs-external.storage-k8s.svc.cluster.local:9090
                DOCTOR_OTEL_ENDPOINT: k8s-svc-compute-k8s-main-otel-opentelemetry-collector-collector.otel.svc.cluster.local:4317
                DOCTOR_OTEL_INSECURE: "true"
                DOCTOR_OTEL_METRIC_INTERVAL: 15s
                DOCTOR_OTEL_SERVICE_NAME: doctor
                DOCTOR_QUERY_HTTP_ADDR: :18080
            image: doctor-query:sha256-d1486b946dd7b5c6e430587656a4b52c2129aac8019c4f8418575c8492635005
            imagePullPolicy: IfNotPresent
            ports:
                - containerPort: 18080
                  name: http
                  protocol: TCP
                  servicePort: 18080
            resources:
                limits:
                    cpu: "1"
                    memory: 1Gi
                requests:
                    cpu: 200m
                    memory: 256Mi
        - type: LoadBalancer
          name: query-edge
          version: 20260515-1449
          dependsOn:
            - query
          payload:
            k8s: /partitions/doctor/payloads/edge.k8s.yaml
          properties:
            listeners:
                - name: http
                  port: 18080
                  protocol: TCP
            serviceType: LoadBalancer
            targets:
                - query
