apiVersion: guardian/v1alpha1
kind: Partition
metadata:
  name: lolipop
  labels:
    role: ai
spec:
  deletionPolicy: orphan
  reconciliation:
    mode: auto
    interval: 1m
  labels:
    stack: k8s
    component: lolipop
    topology: kubernetes
    managedBy: guardian
