apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fetcher-${SUFFIX}-cache
  namespace: ${NAMESPACE}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${FETCHER_PVC_SIZE}
