apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: search-index-data
  namespace: ${NAMESPACE}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${SEARCH_PVC_SIZE}
