apiVersion: v1
kind: Secret
metadata:
  name: monofs-secrets
  namespace: ${NAMESPACE}
type: Opaque
data:
  monofs-token: ${MONOFS_TOKEN}
  minio-access-key: ${MINIO_ACCESS_KEY}
  minio-secret-key: ${MINIO_SECRET_KEY}
