apiVersion: v1
kind: Service
metadata:
  name: fetcher-${SUFFIX}
  namespace: ${NAMESPACE}
spec:
  type: ClusterIP
  selector:
    app: monofs-fetcher
    component: fetcher-${SUFFIX}
  ports:
    - name: grpc
      port: 9200
      targetPort: 9200
