apiVersion: v1
kind: Service
metadata:
  name: monofs-external
  namespace: ${LB_NAMESPACE}
spec:
  type: ${EXTERNAL_SERVICE_TYPE}${EXTERNAL_SERVICE_SPEC}
  selector:
    app: monofs-haproxy
  ports:
    - name: grpc
      port: 9090
      targetPort: 9090
    - name: http
      port: 8080
      targetPort: 8080
    - name: guardian-ui
      port: 8090
      targetPort: 8090
    - name: admin
      port: 18081
      targetPort: 18081
    - name: registry-grpc
      port: 15051
      targetPort: 15051
${LB_NODE_PORTS_SPEC}
${LB_USER_SERVICE_PORTS_SPEC}
