apiVersion: v1
kind: Service
metadata:
  name: node-${SUFFIX}
  namespace: ${NAMESPACE}
spec:
  type: ClusterIP
  selector:
    app: monofs-server
    component: node-${SUFFIX}
  ports:
    - name: grpc
      port: 9000
      targetPort: 9000
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: node-${SUFFIX}-external
  namespace: ${NAMESPACE}
spec:
  type: ${EXTERNAL_SERVICE_TYPE}
  selector:
    app: monofs-server
    component: node-${SUFFIX}
  ports:
    - name: grpc
      port: ${NODE_EXTERNAL_PORT}
      targetPort: 9000
