apiVersion: v1
kind: Service
metadata:
  name: node-${SUFFIX}
  namespace: ${NAMESPACE}
spec:
  type: ClusterIP
  selector:
    app: monofs-server
    component: node-${SUFFIX}
  ports:
    - name: grpc
      port: 9090
      targetPort: 9000
    - name: http
      port: 8080
      targetPort: 8080
