// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.31.1
// source: api/proto/search.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MonoFSSearch_IndexRepository_FullMethodName   = "/monofs.MonoFSSearch/IndexRepository"
	MonoFSSearch_Search_FullMethodName            = "/monofs.MonoFSSearch/Search"
	MonoFSSearch_GetIndexStatus_FullMethodName    = "/monofs.MonoFSSearch/GetIndexStatus"
	MonoFSSearch_ListIndexes_FullMethodName       = "/monofs.MonoFSSearch/ListIndexes"
	MonoFSSearch_RebuildIndex_FullMethodName      = "/monofs.MonoFSSearch/RebuildIndex"
	MonoFSSearch_RebuildAllIndexes_FullMethodName = "/monofs.MonoFSSearch/RebuildAllIndexes"
	MonoFSSearch_DeleteIndex_FullMethodName       = "/monofs.MonoFSSearch/DeleteIndex"
	MonoFSSearch_GetStats_FullMethodName          = "/monofs.MonoFSSearch/GetStats"
)

// MonoFSSearchClient is the client API for MonoFSSearch service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MonoFSSearch provides code search functionality across indexed repositories
type MonoFSSearchClient interface {
	// IndexRepository triggers indexing of a repository (async with status tracking)
	IndexRepository(ctx context.Context, in *IndexRequest, opts ...grpc.CallOption) (*IndexResponse, error)
	// Search performs code search across indexed repositories
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// GetIndexStatus returns the indexing status for a repository
	GetIndexStatus(ctx context.Context, in *IndexStatusRequest, opts ...grpc.CallOption) (*IndexStatusResponse, error)
	// ListIndexes returns all indexed repositories with their status
	ListIndexes(ctx context.Context, in *ListIndexesRequest, opts ...grpc.CallOption) (*ListIndexesResponse, error)
	// RebuildIndex triggers a re-index of a repository
	RebuildIndex(ctx context.Context, in *RebuildIndexRequest, opts ...grpc.CallOption) (*RebuildIndexResponse, error)
	// RebuildAllIndexes triggers re-indexing of all repositories
	RebuildAllIndexes(ctx context.Context, in *RebuildAllIndexesRequest, opts ...grpc.CallOption) (*RebuildAllIndexesResponse, error)
	// DeleteIndex removes the index for a repository
	DeleteIndex(ctx context.Context, in *DeleteIndexRequest, opts ...grpc.CallOption) (*DeleteIndexResponse, error)
	// GetStats returns search service statistics
	GetStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
}

type monoFSSearchClient struct {
	cc grpc.ClientConnInterface
}

func NewMonoFSSearchClient(cc grpc.ClientConnInterface) MonoFSSearchClient {
	return &monoFSSearchClient{cc}
}

func (c *monoFSSearchClient) IndexRepository(ctx context.Context, in *IndexRequest, opts ...grpc.CallOption) (*IndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IndexResponse)
	err := c.cc.Invoke(ctx, MonoFSSearch_IndexRepository_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monoFSSearchClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, MonoFSSearch_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monoFSSearchClient) GetIndexStatus(ctx context.Context, in *IndexStatusRequest, opts ...grpc.CallOption) (*IndexStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IndexStatusResponse)
	err := c.cc.Invoke(ctx, MonoFSSearch_GetIndexStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monoFSSearchClient) ListIndexes(ctx context.Context, in *ListIndexesRequest, opts ...grpc.CallOption) (*ListIndexesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListIndexesResponse)
	err := c.cc.Invoke(ctx, MonoFSSearch_ListIndexes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monoFSSearchClient) RebuildIndex(ctx context.Context, in *RebuildIndexRequest, opts ...grpc.CallOption) (*RebuildIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RebuildIndexResponse)
	err := c.cc.Invoke(ctx, MonoFSSearch_RebuildIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monoFSSearchClient) RebuildAllIndexes(ctx context.Context, in *RebuildAllIndexesRequest, opts ...grpc.CallOption) (*RebuildAllIndexesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RebuildAllIndexesResponse)
	err := c.cc.Invoke(ctx, MonoFSSearch_RebuildAllIndexes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monoFSSearchClient) DeleteIndex(ctx context.Context, in *DeleteIndexRequest, opts ...grpc.CallOption) (*DeleteIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteIndexResponse)
	err := c.cc.Invoke(ctx, MonoFSSearch_DeleteIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monoFSSearchClient) GetStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, MonoFSSearch_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MonoFSSearchServer is the server API for MonoFSSearch service.
// All implementations must embed UnimplementedMonoFSSearchServer
// for forward compatibility.
//
// MonoFSSearch provides code search functionality across indexed repositories
type MonoFSSearchServer interface {
	// IndexRepository triggers indexing of a repository (async with status tracking)
	IndexRepository(context.Context, *IndexRequest) (*IndexResponse, error)
	// Search performs code search across indexed repositories
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	// GetIndexStatus returns the indexing status for a repository
	GetIndexStatus(context.Context, *IndexStatusRequest) (*IndexStatusResponse, error)
	// ListIndexes returns all indexed repositories with their status
	ListIndexes(context.Context, *ListIndexesRequest) (*ListIndexesResponse, error)
	// RebuildIndex triggers a re-index of a repository
	RebuildIndex(context.Context, *RebuildIndexRequest) (*RebuildIndexResponse, error)
	// RebuildAllIndexes triggers re-indexing of all repositories
	RebuildAllIndexes(context.Context, *RebuildAllIndexesRequest) (*RebuildAllIndexesResponse, error)
	// DeleteIndex removes the index for a repository
	DeleteIndex(context.Context, *DeleteIndexRequest) (*DeleteIndexResponse, error)
	// GetStats returns search service statistics
	GetStats(context.Context, *StatsRequest) (*StatsResponse, error)
	mustEmbedUnimplementedMonoFSSearchServer()
}

// UnimplementedMonoFSSearchServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMonoFSSearchServer struct{}

func (UnimplementedMonoFSSearchServer) IndexRepository(context.Context, *IndexRequest) (*IndexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IndexRepository not implemented")
}
func (UnimplementedMonoFSSearchServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedMonoFSSearchServer) GetIndexStatus(context.Context, *IndexStatusRequest) (*IndexStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIndexStatus not implemented")
}
func (UnimplementedMonoFSSearchServer) ListIndexes(context.Context, *ListIndexesRequest) (*ListIndexesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListIndexes not implemented")
}
func (UnimplementedMonoFSSearchServer) RebuildIndex(context.Context, *RebuildIndexRequest) (*RebuildIndexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RebuildIndex not implemented")
}
func (UnimplementedMonoFSSearchServer) RebuildAllIndexes(context.Context, *RebuildAllIndexesRequest) (*RebuildAllIndexesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RebuildAllIndexes not implemented")
}
func (UnimplementedMonoFSSearchServer) DeleteIndex(context.Context, *DeleteIndexRequest) (*DeleteIndexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteIndex not implemented")
}
func (UnimplementedMonoFSSearchServer) GetStats(context.Context, *StatsRequest) (*StatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedMonoFSSearchServer) mustEmbedUnimplementedMonoFSSearchServer() {}
func (UnimplementedMonoFSSearchServer) testEmbeddedByValue()                      {}

// UnsafeMonoFSSearchServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MonoFSSearchServer will
// result in compilation errors.
type UnsafeMonoFSSearchServer interface {
	mustEmbedUnimplementedMonoFSSearchServer()
}

func RegisterMonoFSSearchServer(s grpc.ServiceRegistrar, srv MonoFSSearchServer) {
	// If the following call panics, it indicates UnimplementedMonoFSSearchServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MonoFSSearch_ServiceDesc, srv)
}

func _MonoFSSearch_IndexRepository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonoFSSearchServer).IndexRepository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonoFSSearch_IndexRepository_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonoFSSearchServer).IndexRepository(ctx, req.(*IndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonoFSSearch_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonoFSSearchServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonoFSSearch_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonoFSSearchServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonoFSSearch_GetIndexStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonoFSSearchServer).GetIndexStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonoFSSearch_GetIndexStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonoFSSearchServer).GetIndexStatus(ctx, req.(*IndexStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonoFSSearch_ListIndexes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIndexesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonoFSSearchServer).ListIndexes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonoFSSearch_ListIndexes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonoFSSearchServer).ListIndexes(ctx, req.(*ListIndexesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonoFSSearch_RebuildIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebuildIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonoFSSearchServer).RebuildIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonoFSSearch_RebuildIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonoFSSearchServer).RebuildIndex(ctx, req.(*RebuildIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonoFSSearch_RebuildAllIndexes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebuildAllIndexesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonoFSSearchServer).RebuildAllIndexes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonoFSSearch_RebuildAllIndexes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonoFSSearchServer).RebuildAllIndexes(ctx, req.(*RebuildAllIndexesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonoFSSearch_DeleteIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonoFSSearchServer).DeleteIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonoFSSearch_DeleteIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonoFSSearchServer).DeleteIndex(ctx, req.(*DeleteIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonoFSSearch_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonoFSSearchServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonoFSSearch_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonoFSSearchServer).GetStats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MonoFSSearch_ServiceDesc is the grpc.ServiceDesc for MonoFSSearch service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MonoFSSearch_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "monofs.MonoFSSearch",
	HandlerType: (*MonoFSSearchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IndexRepository",
			Handler:    _MonoFSSearch_IndexRepository_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _MonoFSSearch_Search_Handler,
		},
		{
			MethodName: "GetIndexStatus",
			Handler:    _MonoFSSearch_GetIndexStatus_Handler,
		},
		{
			MethodName: "ListIndexes",
			Handler:    _MonoFSSearch_ListIndexes_Handler,
		},
		{
			MethodName: "RebuildIndex",
			Handler:    _MonoFSSearch_RebuildIndex_Handler,
		},
		{
			MethodName: "RebuildAllIndexes",
			Handler:    _MonoFSSearch_RebuildAllIndexes_Handler,
		},
		{
			MethodName: "DeleteIndex",
			Handler:    _MonoFSSearch_DeleteIndex_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _MonoFSSearch_GetStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/search.proto",
}
