// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: api/proto/search.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IndexStatus represents the state of an index
type IndexStatus int32

const (
	IndexStatus_INDEX_STATUS_UNKNOWN   IndexStatus = 0
	IndexStatus_INDEX_STATUS_QUEUED    IndexStatus = 1 // Waiting in queue
	IndexStatus_INDEX_STATUS_INDEXING  IndexStatus = 2 // Currently indexing
	IndexStatus_INDEX_STATUS_READY     IndexStatus = 3 // Index is ready for search
	IndexStatus_INDEX_STATUS_ERROR     IndexStatus = 4 // Indexing failed
	IndexStatus_INDEX_STATUS_NOT_FOUND IndexStatus = 5 // No index exists
)

// Enum value maps for IndexStatus.
var (
	IndexStatus_name = map[int32]string{
		0: "INDEX_STATUS_UNKNOWN",
		1: "INDEX_STATUS_QUEUED",
		2: "INDEX_STATUS_INDEXING",
		3: "INDEX_STATUS_READY",
		4: "INDEX_STATUS_ERROR",
		5: "INDEX_STATUS_NOT_FOUND",
	}
	IndexStatus_value = map[string]int32{
		"INDEX_STATUS_UNKNOWN":   0,
		"INDEX_STATUS_QUEUED":    1,
		"INDEX_STATUS_INDEXING":  2,
		"INDEX_STATUS_READY":     3,
		"INDEX_STATUS_ERROR":     4,
		"INDEX_STATUS_NOT_FOUND": 5,
	}
)

func (x IndexStatus) Enum() *IndexStatus {
	p := new(IndexStatus)
	*p = x
	return p
}

func (x IndexStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IndexStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_search_proto_enumTypes[0].Descriptor()
}

func (IndexStatus) Type() protoreflect.EnumType {
	return &file_api_proto_search_proto_enumTypes[0]
}

func (x IndexStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IndexStatus.Descriptor instead.
func (IndexStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_search_proto_rawDescGZIP(), []int{0}
}

// IndexRequest triggers indexing for a repository
type IndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StorageId     string                 `protobuf:"bytes,1,opt,name=storage_id,json=storageId,proto3" json:"storage_id,omitempty"`       // Internal storage ID (SHA-256 hash)
	DisplayPath   string                 `protobuf:"bytes,2,opt,name=display_path,json=displayPath,proto3" json:"display_path,omitempty"` // Human-readable path (e.g., github_com/owner/repo)
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`                              // Source identifier (Git URL, Go module path, etc.)
	Ref           string                 `protobuf:"bytes,4,opt,name=ref,proto3" json:"ref,omitempty"`                                    // Reference (branch for Git, version for Go, etc.)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexRequest) Reset() {
	*x = IndexRequest{}
	mi := &file_api_proto_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexRequest) ProtoMessage() {}

func (x *IndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexRequest.ProtoReflect.Descriptor instead.
func (*IndexRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_search_proto_rawDescGZIP(), []int{0}
}

func (x *IndexRequest) GetStorageId() string {
	if x != nil {
		return x.StorageId
	}
	return ""
}

func (x *IndexRequest) GetDisplayPath() string {
	if x != nil {
		return x.DisplayPath
	}
	return ""
}

func (x *IndexRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *IndexRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

// IndexResponse confirms indexing was queued
type IndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queued        bool                   `protobuf:"varint,1,opt,name=queued,proto3" json:"queued,omitempty"`           // True if successfully queued
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`          // Status message
	JobId         string                 `protobuf:"bytes,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"` // Job ID for tracking
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexResponse) Reset() {
	*x = IndexResponse{}
	mi := &file_api_proto_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexResponse) ProtoMessage() {}

func (x *IndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexResponse.ProtoReflect.Descriptor instead.
func (*IndexResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_search_proto_rawDescGZIP(), []int{1}
}

func (x *IndexResponse) GetQueued() bool {
	if x != nil {
		return x.Queued
	}
	return false
}

func (x *IndexResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *IndexResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

// SearchRequest performs a code search
type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`                                       // Search query (supports regex if enabled)
	StorageId     string                 `protobuf:"bytes,2,opt,name=storage_id,json=storageId,proto3" json:"storage_id,omitempty"`              // Optional: limit to specific repository
	MaxResults    int32                  `protobuf:"varint,3,opt,name=max_results,json=maxResults,proto3" json:"max_results,omitempty"`          // Maximum results (default: 100)
	CaseSensitive bool                   `protobuf:"varint,4,opt,name=case_sensitive,json=caseSensitive,proto3" json:"case_sensitive,omitempty"` // Case-sensitive search
	Regex         bool                   `protobuf:"varint,5,opt,name=regex,proto3" json:"regex,omitempty"`                                      // Treat query as regex
	FilePatterns  []string               `protobuf:"bytes,6,rep,name=file_patterns,json=filePatterns,proto3" json:"file_patterns,omitempty"`     // Optional: file glob patterns (e.g., "*.go")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_api_proto_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_search_proto_rawDescGZIP(), []int{2}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetStorageId() string {
	if x != nil {
		return x.StorageId
	}
	return ""
}

func (x *SearchRequest) GetMaxResults() int32 {
	if x != nil {
		return x.MaxResults
	}
	return 0
}

func (x *SearchRequest) GetCaseSensitive() bool {
	if x != nil {
		return x.CaseSensitive
	}
	return false
}

func (x *SearchRequest) GetRegex() bool {
	if x != nil {
		return x.Regex
	}
	return false
}

func (x *SearchRequest) GetFilePatterns() []string {
	if x != nil {
		return x.FilePatterns
	}
	return nil
}

// SearchResponse contains search results
type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	TotalMatches  int64                  `protobuf:"varint,2,opt,name=total_matches,json=totalMatches,proto3" json:"total_matches,omitempty"`    // Total number of matches found
	FilesSearched int64                  `protobuf:"varint,3,opt,name=files_searched,json=filesSearched,proto3" json:"files_searched,omitempty"` // Number of files searched
	DurationMs    int64                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`          // Search duration in milliseconds
	Truncated     bool                   `protobuf:"varint,5,opt,name=truncated,proto3" json:"truncated,omitempty"`                              // True if results were truncated
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_api_proto_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_search_proto_rawDescGZIP(), []int{3}
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchResponse) GetTotalMatches() int64 {
	if x != nil {
		return x.TotalMatches
	}
	return 0
}

func (x *SearchResponse) GetFilesSearched() int64 {
	if x != nil {
		return x.FilesSearched
	}
	return 0
}

func (x *SearchResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *SearchResponse) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

// SearchResult represents a single search match
type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StorageId     string                 `protobuf:"bytes,1,opt,name=storage_id,json=storageId,proto3" json:"storage_id,omitempty"`             // Repository storage ID
	DisplayPath   string                 `protobuf:"bytes,2,opt,name=display_path,json=displayPath,proto3" json:"display_path,omitempty"`       // Repository display path
	FilePath      string                 `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`                // File path within repository
	LineNumber    int32                  `protobuf:"varint,4,opt,name=line_number,json=lineNumber,proto3" json:"line_number,omitempty"`         // Line number (1-based)
	LineContent   string                 `protobuf:"bytes,5,opt,name=line_content,json=lineContent,proto3" json:"line_content,omitempty"`       // Content of the matched line
	Matches       []*MatchRange          `protobuf:"bytes,6,rep,name=matches,proto3" json:"matches,omitempty"`                                  // Match positions within line
	BeforeContext string                 `protobuf:"bytes,7,opt,name=before_context,json=beforeContext,proto3" json:"before_context,omitempty"` // Line before match (optional)
	AfterContext  string                 `protobuf:"bytes,8,opt,name=after_context,json=afterContext,proto3" json:"after_context,omitempty"`    // Line after match (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_api_proto_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_api_proto_search_proto_rawDescGZIP(), []int{4}
}

func (x *SearchResult) GetStorageId() string {
	if x != nil {
		return x.StorageId
	}
	return ""
}

func (x *SearchResult) GetDisplayPath() string {
	if x != nil {
		return x.DisplayPath
	}
	return ""
}

func (x *SearchResult) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *SearchResult) GetLineNumber() int32 {
	if x != nil {
		return x.LineNumber
	}
	return 0
}

func (x *SearchResult) GetLineContent() string {
	if x != nil {
		return x.LineContent
	}
	return ""
}

func (x *SearchResult) GetMatches() []*MatchRange {
	if x != nil {
		return x.Matches
	}
	return nil
}

func (x *SearchResult) GetBeforeContext() string {
	if x != nil {
		return x.BeforeContext
	}
	return ""
}

func (x *SearchResult) GetAfterContext() string {
	if x != nil {
		return x.AfterContext
	}
	return ""
}

// MatchRange indicates a match position within a line
type MatchRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         int32                  `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"` // Start byte offset
	End           int32                  `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`     // End byte offset
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchRange) Reset() {
	*x = MatchRange{}
	mi := &file_api_proto_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchRange) ProtoMessage() {}

func (x *MatchRange) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchRange.ProtoReflect.Descriptor instead.
func (*MatchRange) Descriptor() ([]byte, []int) {
	return file_api_proto_search_proto_rawDescGZIP(), []int{5}
}

func (x *MatchRange) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *MatchRange) GetEnd() int32 {
	if x != nil {
		return x.End
	}
	return 0
}

// IndexStatusRequest queries status of a repository index
type IndexStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StorageId     string                 `protobuf:"bytes,1,opt,name=storage_id,json=storageId,proto3" json:"storage_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexStatusRequest) Reset() {
	*x = IndexStatusRequest{}
	mi := &file_api_proto_search_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexStatusRequest) ProtoMessage() {}

func (x *IndexStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexStatusRequest.ProtoReflect.Descriptor instead.
func (*IndexStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_search_proto_rawDescGZIP(), []int{6}
}

func (x *IndexStatusRequest) GetStorageId() string {
	if x != nil {
		return x.StorageId
	}
	return ""
}

// IndexStatusResponse contains index status
type IndexStatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StorageId      string                 `protobuf:"bytes,1,opt,name=storage_id,json=storageId,proto3" json:"storage_id,omitempty"`
	DisplayPath    string                 `protobuf:"bytes,2,opt,name=display_path,json=displayPath,proto3" json:"display_path,omitempty"`
	Status         IndexStatus            `protobuf:"varint,3,opt,name=status,proto3,enum=monofs.IndexStatus" json:"status,omitempty"`                 // Current indexing status
	FilesCount     int64                  `protobuf:"varint,4,opt,name=files_count,json=filesCount,proto3" json:"files_count,omitempty"`               // Number of files indexed
	IndexSizeBytes int64                  `protobuf:"varint,5,opt,name=index_size_bytes,json=indexSizeBytes,proto3" json:"index_size_bytes,omitempty"` // Index size on disk
	LastIndexed    string                 `protobuf:"bytes,6,opt,name=last_indexed,json=lastIndexed,proto3" json:"last_indexed,omitempty"`             // ISO timestamp of last successful index
	ErrorMessage   string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`          // Error message if status is ERROR
	Progress       float32                `protobuf:"fixed32,8,opt,name=progress,proto3" json:"progress,omitempty"`                                    // Indexing progress (0.0 - 1.0) if INDEXING
	QueuedAt       string                 `protobuf:"bytes,9,opt,name=queued_at,json=queuedAt,proto3" json:"queued_at,omitempty"`                      // When job was queued
	StartedAt      string                 `protobuf:"bytes,10,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`                  // When indexing started
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IndexStatusResponse) Reset() {
	*x = IndexStatusResponse{}
	mi := &file_api_proto_search_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexStatusResponse) ProtoMessage() {}

func (x *IndexStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexStatusResponse.ProtoReflect.Descriptor instead.
func (*IndexStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_search_proto_rawDescGZIP(), []int{7}
}

func (x *IndexStatusResponse) GetStorageId() string {
	if x != nil {
		return x.StorageId
	}
	return ""
}

func (x *IndexStatusResponse) GetDisplayPath() string {
	if x != nil {
		return x.DisplayPath
	}
	return ""
}

func (x *IndexStatusResponse) GetStatus() IndexStatus {
	if x != nil {
		return x.Status
	}
	return IndexStatus_INDEX_STATUS_UNKNOWN
}

func (x *IndexStatusResponse) GetFilesCount() int64 {
	if x != nil {
		return x.FilesCount
	}
	return 0
}

func (x *IndexStatusResponse) GetIndexSizeBytes() int64 {
	if x != nil {
		return x.IndexSizeBytes
	}
	return 0
}

func (x *IndexStatusResponse) GetLastIndexed() string {
	if x != nil {
		return x.LastIndexed
	}
	return ""
}

func (x *IndexStatusResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *IndexStatusResponse) GetProgress() float32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *IndexStatusResponse) GetQueuedAt() string {
	if x != nil {
		return x.QueuedAt
	}
	return ""
}

func (x *IndexStatusResponse) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

// ListIndexesRequest queries all indexes
type ListIndexesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIndexesRequest) Reset() {
	*x = ListIndexesRequest{}
	mi := &file_api_proto_search_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIndexesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIndexesRequest) ProtoMessage() {}

func (x *ListIndexesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIndexesRequest.ProtoReflect.Descriptor instead.
func (*ListIndexesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_search_proto_rawDescGZIP(), []int{8}
}

// ListIndexesResponse contains all index statuses
type ListIndexesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Indexes       []*IndexStatusResponse `protobuf:"bytes,1,rep,name=indexes,proto3" json:"indexes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIndexesResponse) Reset() {
	*x = ListIndexesResponse{}
	mi := &file_api_proto_search_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIndexesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIndexesResponse) ProtoMessage() {}

func (x *ListIndexesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIndexesResponse.ProtoReflect.Descriptor instead.
func (*ListIndexesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_search_proto_rawDescGZIP(), []int{9}
}

func (x *ListIndexesResponse) GetIndexes() []*IndexStatusResponse {
	if x != nil {
		return x.Indexes
	}
	return nil
}

// RebuildIndexRequest triggers re-indexing of a repository
type RebuildIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StorageId     string                 `protobuf:"bytes,1,opt,name=storage_id,json=storageId,proto3" json:"storage_id,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"` // Rebuild even if already up-to-date
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebuildIndexRequest) Reset() {
	*x = RebuildIndexRequest{}
	mi := &file_api_proto_search_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebuildIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebuildIndexRequest) ProtoMessage() {}

func (x *RebuildIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebuildIndexRequest.ProtoReflect.Descriptor instead.
func (*RebuildIndexRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_search_proto_rawDescGZIP(), []int{10}
}

func (x *RebuildIndexRequest) GetStorageId() string {
	if x != nil {
		return x.StorageId
	}
	return ""
}

func (x *RebuildIndexRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// RebuildIndexResponse confirms rebuild was queued
type RebuildIndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queued        bool                   `protobuf:"varint,1,opt,name=queued,proto3" json:"queued,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	JobId         string                 `protobuf:"bytes,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebuildIndexResponse) Reset() {
	*x = RebuildIndexResponse{}
	mi := &file_api_proto_search_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebuildIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebuildIndexResponse) ProtoMessage() {}

func (x *RebuildIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebuildIndexResponse.ProtoReflect.Descriptor instead.
func (*RebuildIndexResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_search_proto_rawDescGZIP(), []int{11}
}

func (x *RebuildIndexResponse) GetQueued() bool {
	if x != nil {
		return x.Queued
	}
	return false
}

func (x *RebuildIndexResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RebuildIndexResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

// RebuildAllIndexesRequest triggers re-indexing of all repositories
type RebuildAllIndexesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Force         bool                   `protobuf:"varint,1,opt,name=force,proto3" json:"force,omitempty"` // Rebuild all, even if up-to-date
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebuildAllIndexesRequest) Reset() {
	*x = RebuildAllIndexesRequest{}
	mi := &file_api_proto_search_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebuildAllIndexesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebuildAllIndexesRequest) ProtoMessage() {}

func (x *RebuildAllIndexesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebuildAllIndexesRequest.ProtoReflect.Descriptor instead.
func (*RebuildAllIndexesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_search_proto_rawDescGZIP(), []int{12}
}

func (x *RebuildAllIndexesRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// RebuildAllIndexesResponse confirms rebuilds were queued
type RebuildAllIndexesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueuedCount   int32                  `protobuf:"varint,1,opt,name=queued_count,json=queuedCount,proto3" json:"queued_count,omitempty"` // Number of repositories queued for rebuild
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebuildAllIndexesResponse) Reset() {
	*x = RebuildAllIndexesResponse{}
	mi := &file_api_proto_search_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebuildAllIndexesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebuildAllIndexesResponse) ProtoMessage() {}

func (x *RebuildAllIndexesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebuildAllIndexesResponse.ProtoReflect.Descriptor instead.
func (*RebuildAllIndexesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_search_proto_rawDescGZIP(), []int{13}
}

func (x *RebuildAllIndexesResponse) GetQueuedCount() int32 {
	if x != nil {
		return x.QueuedCount
	}
	return 0
}

func (x *RebuildAllIndexesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// DeleteIndexRequest removes an index
type DeleteIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StorageId     string                 `protobuf:"bytes,1,opt,name=storage_id,json=storageId,proto3" json:"storage_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteIndexRequest) Reset() {
	*x = DeleteIndexRequest{}
	mi := &file_api_proto_search_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIndexRequest) ProtoMessage() {}

func (x *DeleteIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIndexRequest.ProtoReflect.Descriptor instead.
func (*DeleteIndexRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_search_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteIndexRequest) GetStorageId() string {
	if x != nil {
		return x.StorageId
	}
	return ""
}

// DeleteIndexResponse confirms deletion
type DeleteIndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteIndexResponse) Reset() {
	*x = DeleteIndexResponse{}
	mi := &file_api_proto_search_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIndexResponse) ProtoMessage() {}

func (x *DeleteIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIndexResponse.ProtoReflect.Descriptor instead.
func (*DeleteIndexResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_search_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteIndexResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteIndexResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// StatsRequest queries service statistics
type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_api_proto_search_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_search_proto_rawDescGZIP(), []int{16}
}

// StatsResponse contains service statistics
type StatsResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TotalIndexes        int64                  `protobuf:"varint,1,opt,name=total_indexes,json=totalIndexes,proto3" json:"total_indexes,omitempty"`                          // Total number of indexed repositories
	TotalFilesIndexed   int64                  `protobuf:"varint,2,opt,name=total_files_indexed,json=totalFilesIndexed,proto3" json:"total_files_indexed,omitempty"`         // Total files across all indexes
	TotalIndexSizeBytes int64                  `protobuf:"varint,3,opt,name=total_index_size_bytes,json=totalIndexSizeBytes,proto3" json:"total_index_size_bytes,omitempty"` // Total index storage used
	QueueLength         int32                  `protobuf:"varint,4,opt,name=queue_length,json=queueLength,proto3" json:"queue_length,omitempty"`                             // Jobs waiting in queue
	ActiveJobs          int32                  `protobuf:"varint,5,opt,name=active_jobs,json=activeJobs,proto3" json:"active_jobs,omitempty"`                                // Jobs currently being indexed
	SearchesTotal       int64                  `protobuf:"varint,6,opt,name=searches_total,json=searchesTotal,proto3" json:"searches_total,omitempty"`                       // Total searches performed
	AvgSearchDurationMs int64                  `protobuf:"varint,7,opt,name=avg_search_duration_ms,json=avgSearchDurationMs,proto3" json:"avg_search_duration_ms,omitempty"` // Average search duration
	Uptime              string                 `protobuf:"bytes,8,opt,name=uptime,proto3" json:"uptime,omitempty"`                                                           // Service uptime
	JobsQueued          int64                  `protobuf:"varint,9,opt,name=jobs_queued,json=jobsQueued,proto3" json:"jobs_queued,omitempty"`                                // Total jobs ever queued
	JobsCompleted       int64                  `protobuf:"varint,10,opt,name=jobs_completed,json=jobsCompleted,proto3" json:"jobs_completed,omitempty"`                      // Total jobs completed successfully
	JobsFailed          int64                  `protobuf:"varint,11,opt,name=jobs_failed,json=jobsFailed,proto3" json:"jobs_failed,omitempty"`                               // Total jobs that failed
	JobsRejected        int64                  `protobuf:"varint,12,opt,name=jobs_rejected,json=jobsRejected,proto3" json:"jobs_rejected,omitempty"`                         // Total jobs rejected (queue full)
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_api_proto_search_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_search_proto_rawDescGZIP(), []int{17}
}

func (x *StatsResponse) GetTotalIndexes() int64 {
	if x != nil {
		return x.TotalIndexes
	}
	return 0
}

func (x *StatsResponse) GetTotalFilesIndexed() int64 {
	if x != nil {
		return x.TotalFilesIndexed
	}
	return 0
}

func (x *StatsResponse) GetTotalIndexSizeBytes() int64 {
	if x != nil {
		return x.TotalIndexSizeBytes
	}
	return 0
}

func (x *StatsResponse) GetQueueLength() int32 {
	if x != nil {
		return x.QueueLength
	}
	return 0
}

func (x *StatsResponse) GetActiveJobs() int32 {
	if x != nil {
		return x.ActiveJobs
	}
	return 0
}

func (x *StatsResponse) GetSearchesTotal() int64 {
	if x != nil {
		return x.SearchesTotal
	}
	return 0
}

func (x *StatsResponse) GetAvgSearchDurationMs() int64 {
	if x != nil {
		return x.AvgSearchDurationMs
	}
	return 0
}

func (x *StatsResponse) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

func (x *StatsResponse) GetJobsQueued() int64 {
	if x != nil {
		return x.JobsQueued
	}
	return 0
}

func (x *StatsResponse) GetJobsCompleted() int64 {
	if x != nil {
		return x.JobsCompleted
	}
	return 0
}

func (x *StatsResponse) GetJobsFailed() int64 {
	if x != nil {
		return x.JobsFailed
	}
	return 0
}

func (x *StatsResponse) GetJobsRejected() int64 {
	if x != nil {
		return x.JobsRejected
	}
	return 0
}

var File_api_proto_search_proto protoreflect.FileDescriptor

const file_api_proto_search_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/search.proto\x12\x06monofs\"z\n" +
	"\fIndexRequest\x12\x1d\n" +
	"\n" +
	"storage_id\x18\x01 \x01(\tR\tstorageId\x12!\n" +
	"\fdisplay_path\x18\x02 \x01(\tR\vdisplayPath\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x10\n" +
	"\x03ref\x18\x04 \x01(\tR\x03ref\"X\n" +
	"\rIndexResponse\x12\x16\n" +
	"\x06queued\x18\x01 \x01(\bR\x06queued\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x15\n" +
	"\x06job_id\x18\x03 \x01(\tR\x05jobId\"\xc7\x01\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1d\n" +
	"\n" +
	"storage_id\x18\x02 \x01(\tR\tstorageId\x12\x1f\n" +
	"\vmax_results\x18\x03 \x01(\x05R\n" +
	"maxResults\x12%\n" +
	"\x0ecase_sensitive\x18\x04 \x01(\bR\rcaseSensitive\x12\x14\n" +
	"\x05regex\x18\x05 \x01(\bR\x05regex\x12#\n" +
	"\rfile_patterns\x18\x06 \x03(\tR\ffilePatterns\"\xcb\x01\n" +
	"\x0eSearchResponse\x12.\n" +
	"\aresults\x18\x01 \x03(\v2\x14.monofs.SearchResultR\aresults\x12#\n" +
	"\rtotal_matches\x18\x02 \x01(\x03R\ftotalMatches\x12%\n" +
	"\x0efiles_searched\x18\x03 \x01(\x03R\rfilesSearched\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\x12\x1c\n" +
	"\ttruncated\x18\x05 \x01(\bR\ttruncated\"\xab\x02\n" +
	"\fSearchResult\x12\x1d\n" +
	"\n" +
	"storage_id\x18\x01 \x01(\tR\tstorageId\x12!\n" +
	"\fdisplay_path\x18\x02 \x01(\tR\vdisplayPath\x12\x1b\n" +
	"\tfile_path\x18\x03 \x01(\tR\bfilePath\x12\x1f\n" +
	"\vline_number\x18\x04 \x01(\x05R\n" +
	"lineNumber\x12!\n" +
	"\fline_content\x18\x05 \x01(\tR\vlineContent\x12,\n" +
	"\amatches\x18\x06 \x03(\v2\x12.monofs.MatchRangeR\amatches\x12%\n" +
	"\x0ebefore_context\x18\a \x01(\tR\rbeforeContext\x12#\n" +
	"\rafter_context\x18\b \x01(\tR\fafterContext\"4\n" +
	"\n" +
	"MatchRange\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x05R\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x05R\x03end\"3\n" +
	"\x12IndexStatusRequest\x12\x1d\n" +
	"\n" +
	"storage_id\x18\x01 \x01(\tR\tstorageId\"\xef\x02\n" +
	"\x13IndexStatusResponse\x12\x1d\n" +
	"\n" +
	"storage_id\x18\x01 \x01(\tR\tstorageId\x12!\n" +
	"\fdisplay_path\x18\x02 \x01(\tR\vdisplayPath\x12+\n" +
	"\x06status\x18\x03 \x01(\x0e2\x13.monofs.IndexStatusR\x06status\x12\x1f\n" +
	"\vfiles_count\x18\x04 \x01(\x03R\n" +
	"filesCount\x12(\n" +
	"\x10index_size_bytes\x18\x05 \x01(\x03R\x0eindexSizeBytes\x12!\n" +
	"\flast_indexed\x18\x06 \x01(\tR\vlastIndexed\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\x12\x1a\n" +
	"\bprogress\x18\b \x01(\x02R\bprogress\x12\x1b\n" +
	"\tqueued_at\x18\t \x01(\tR\bqueuedAt\x12\x1d\n" +
	"\n" +
	"started_at\x18\n" +
	" \x01(\tR\tstartedAt\"\x14\n" +
	"\x12ListIndexesRequest\"L\n" +
	"\x13ListIndexesResponse\x125\n" +
	"\aindexes\x18\x01 \x03(\v2\x1b.monofs.IndexStatusResponseR\aindexes\"J\n" +
	"\x13RebuildIndexRequest\x12\x1d\n" +
	"\n" +
	"storage_id\x18\x01 \x01(\tR\tstorageId\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"_\n" +
	"\x14RebuildIndexResponse\x12\x16\n" +
	"\x06queued\x18\x01 \x01(\bR\x06queued\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x15\n" +
	"\x06job_id\x18\x03 \x01(\tR\x05jobId\"0\n" +
	"\x18RebuildAllIndexesRequest\x12\x14\n" +
	"\x05force\x18\x01 \x01(\bR\x05force\"X\n" +
	"\x19RebuildAllIndexesResponse\x12!\n" +
	"\fqueued_count\x18\x01 \x01(\x05R\vqueuedCount\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"3\n" +
	"\x12DeleteIndexRequest\x12\x1d\n" +
	"\n" +
	"storage_id\x18\x01 \x01(\tR\tstorageId\"I\n" +
	"\x13DeleteIndexResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x0e\n" +
	"\fStatsRequest\"\xdf\x03\n" +
	"\rStatsResponse\x12#\n" +
	"\rtotal_indexes\x18\x01 \x01(\x03R\ftotalIndexes\x12.\n" +
	"\x13total_files_indexed\x18\x02 \x01(\x03R\x11totalFilesIndexed\x123\n" +
	"\x16total_index_size_bytes\x18\x03 \x01(\x03R\x13totalIndexSizeBytes\x12!\n" +
	"\fqueue_length\x18\x04 \x01(\x05R\vqueueLength\x12\x1f\n" +
	"\vactive_jobs\x18\x05 \x01(\x05R\n" +
	"activeJobs\x12%\n" +
	"\x0esearches_total\x18\x06 \x01(\x03R\rsearchesTotal\x123\n" +
	"\x16avg_search_duration_ms\x18\a \x01(\x03R\x13avgSearchDurationMs\x12\x16\n" +
	"\x06uptime\x18\b \x01(\tR\x06uptime\x12\x1f\n" +
	"\vjobs_queued\x18\t \x01(\x03R\n" +
	"jobsQueued\x12%\n" +
	"\x0ejobs_completed\x18\n" +
	" \x01(\x03R\rjobsCompleted\x12\x1f\n" +
	"\vjobs_failed\x18\v \x01(\x03R\n" +
	"jobsFailed\x12#\n" +
	"\rjobs_rejected\x18\f \x01(\x03R\fjobsRejected*\xa7\x01\n" +
	"\vIndexStatus\x12\x18\n" +
	"\x14INDEX_STATUS_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13INDEX_STATUS_QUEUED\x10\x01\x12\x19\n" +
	"\x15INDEX_STATUS_INDEXING\x10\x02\x12\x16\n" +
	"\x12INDEX_STATUS_READY\x10\x03\x12\x16\n" +
	"\x12INDEX_STATUS_ERROR\x10\x04\x12\x1a\n" +
	"\x16INDEX_STATUS_NOT_FOUND\x10\x052\xc0\x04\n" +
	"\fMonoFSSearch\x12>\n" +
	"\x0fIndexRepository\x12\x14.monofs.IndexRequest\x1a\x15.monofs.IndexResponse\x127\n" +
	"\x06Search\x12\x15.monofs.SearchRequest\x1a\x16.monofs.SearchResponse\x12I\n" +
	"\x0eGetIndexStatus\x12\x1a.monofs.IndexStatusRequest\x1a\x1b.monofs.IndexStatusResponse\x12F\n" +
	"\vListIndexes\x12\x1a.monofs.ListIndexesRequest\x1a\x1b.monofs.ListIndexesResponse\x12I\n" +
	"\fRebuildIndex\x12\x1b.monofs.RebuildIndexRequest\x1a\x1c.monofs.RebuildIndexResponse\x12X\n" +
	"\x11RebuildAllIndexes\x12 .monofs.RebuildAllIndexesRequest\x1a!.monofs.RebuildAllIndexesResponse\x12F\n" +
	"\vDeleteIndex\x12\x1a.monofs.DeleteIndexRequest\x1a\x1b.monofs.DeleteIndexResponse\x127\n" +
	"\bGetStats\x12\x14.monofs.StatsRequest\x1a\x15.monofs.StatsResponseB$Z\"github.com/radryc/monofs/api/protob\x06proto3"

var (
	file_api_proto_search_proto_rawDescOnce sync.Once
	file_api_proto_search_proto_rawDescData []byte
)

func file_api_proto_search_proto_rawDescGZIP() []byte {
	file_api_proto_search_proto_rawDescOnce.Do(func() {
		file_api_proto_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_search_proto_rawDesc), len(file_api_proto_search_proto_rawDesc)))
	})
	return file_api_proto_search_proto_rawDescData
}

var file_api_proto_search_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_search_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_api_proto_search_proto_goTypes = []any{
	(IndexStatus)(0),                  // 0: monofs.IndexStatus
	(*IndexRequest)(nil),              // 1: monofs.IndexRequest
	(*IndexResponse)(nil),             // 2: monofs.IndexResponse
	(*SearchRequest)(nil),             // 3: monofs.SearchRequest
	(*SearchResponse)(nil),            // 4: monofs.SearchResponse
	(*SearchResult)(nil),              // 5: monofs.SearchResult
	(*MatchRange)(nil),                // 6: monofs.MatchRange
	(*IndexStatusRequest)(nil),        // 7: monofs.IndexStatusRequest
	(*IndexStatusResponse)(nil),       // 8: monofs.IndexStatusResponse
	(*ListIndexesRequest)(nil),        // 9: monofs.ListIndexesRequest
	(*ListIndexesResponse)(nil),       // 10: monofs.ListIndexesResponse
	(*RebuildIndexRequest)(nil),       // 11: monofs.RebuildIndexRequest
	(*RebuildIndexResponse)(nil),      // 12: monofs.RebuildIndexResponse
	(*RebuildAllIndexesRequest)(nil),  // 13: monofs.RebuildAllIndexesRequest
	(*RebuildAllIndexesResponse)(nil), // 14: monofs.RebuildAllIndexesResponse
	(*DeleteIndexRequest)(nil),        // 15: monofs.DeleteIndexRequest
	(*DeleteIndexResponse)(nil),       // 16: monofs.DeleteIndexResponse
	(*StatsRequest)(nil),              // 17: monofs.StatsRequest
	(*StatsResponse)(nil),             // 18: monofs.StatsResponse
}
var file_api_proto_search_proto_depIdxs = []int32{
	5,  // 0: monofs.SearchResponse.results:type_name -> monofs.SearchResult
	6,  // 1: monofs.SearchResult.matches:type_name -> monofs.MatchRange
	0,  // 2: monofs.IndexStatusResponse.status:type_name -> monofs.IndexStatus
	8,  // 3: monofs.ListIndexesResponse.indexes:type_name -> monofs.IndexStatusResponse
	1,  // 4: monofs.MonoFSSearch.IndexRepository:input_type -> monofs.IndexRequest
	3,  // 5: monofs.MonoFSSearch.Search:input_type -> monofs.SearchRequest
	7,  // 6: monofs.MonoFSSearch.GetIndexStatus:input_type -> monofs.IndexStatusRequest
	9,  // 7: monofs.MonoFSSearch.ListIndexes:input_type -> monofs.ListIndexesRequest
	11, // 8: monofs.MonoFSSearch.RebuildIndex:input_type -> monofs.RebuildIndexRequest
	13, // 9: monofs.MonoFSSearch.RebuildAllIndexes:input_type -> monofs.RebuildAllIndexesRequest
	15, // 10: monofs.MonoFSSearch.DeleteIndex:input_type -> monofs.DeleteIndexRequest
	17, // 11: monofs.MonoFSSearch.GetStats:input_type -> monofs.StatsRequest
	2,  // 12: monofs.MonoFSSearch.IndexRepository:output_type -> monofs.IndexResponse
	4,  // 13: monofs.MonoFSSearch.Search:output_type -> monofs.SearchResponse
	8,  // 14: monofs.MonoFSSearch.GetIndexStatus:output_type -> monofs.IndexStatusResponse
	10, // 15: monofs.MonoFSSearch.ListIndexes:output_type -> monofs.ListIndexesResponse
	12, // 16: monofs.MonoFSSearch.RebuildIndex:output_type -> monofs.RebuildIndexResponse
	14, // 17: monofs.MonoFSSearch.RebuildAllIndexes:output_type -> monofs.RebuildAllIndexesResponse
	16, // 18: monofs.MonoFSSearch.DeleteIndex:output_type -> monofs.DeleteIndexResponse
	18, // 19: monofs.MonoFSSearch.GetStats:output_type -> monofs.StatsResponse
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_search_proto_init() }
func file_api_proto_search_proto_init() {
	if File_api_proto_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_search_proto_rawDesc), len(file_api_proto_search_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_search_proto_goTypes,
		DependencyIndexes: file_api_proto_search_proto_depIdxs,
		EnumInfos:         file_api_proto_search_proto_enumTypes,
		MessageInfos:      file_api_proto_search_proto_msgTypes,
	}.Build()
	File_api_proto_search_proto = out.File
	file_api_proto_search_proto_goTypes = nil
	file_api_proto_search_proto_depIdxs = nil
}
