apiVersion: apps/v1
kind: Deployment
metadata:
  name: guardiand
  namespace: ${NAMESPACE}
  labels:
    app: guardiand
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guardiand
  template:
    metadata:
      labels:
        app: guardiand
    spec:
      serviceAccountName: guardian
      containers:
        - name: guardiand
          image: ${GUARDIAN_IMAGE}
          env:
            - name: GUARDIAN_MONOFS_ROUTER
              value: "${GUARDIAN_MONOFS_ROUTER}"
            - name: GUARDIAN_MONOFS_CLIENT_API_ENDPOINT
              value: "${GUARDIAN_MONOFS_CLIENT_API_ENDPOINT}"
            - name: GUARDIAN_MONOFS_USE_EXTERNAL_ADDRESSES
              value: "${GUARDIAN_MONOFS_USE_EXTERNAL_ADDRESSES}"
            - name: GUARDIAN_MONOFS_CLIENT_USE_EXTERNAL_ADDRESSES
              value: "${GUARDIAN_MONOFS_CLIENT_USE_EXTERNAL_ADDRESSES}"
            - name: GUARDIAN_MONOFS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: guardian-secrets
                  key: monofs-token
            - name: GUARDIAN_CLIENT_DISCOVERY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: guardian-secrets
                  key: client-discovery-token
            - name: GUARDIAN_PUSHERS
              value: "${GUARDIAN_PUSHERS}"
            - name: GUARDIAN_UI_LISTEN
              value: "${GUARDIAN_UI_LISTEN}"
            - name: GUARDIAN_UI_BASE_URL
              value: "${GUARDIAN_UI_BASE_URL}"
          ports:
            - containerPort: ${GUARDIAN_UI_PORT}
          volumeMounts:
            - name: secrets
              mountPath: /etc/guardian/secrets
              readOnly: true
      volumes:
        - name: secrets
          secret:
            secretName: guardian-secrets
