apiVersion: apps/v1
kind: Deployment
metadata:
  name: guardian-pusher-aws
  namespace: ${NAMESPACE}
  labels:
    app: guardian-pusher-aws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guardian-pusher-aws
  template:
    metadata:
      labels:
        app: guardian-pusher-aws
    spec:
      serviceAccountName: guardian
      containers:
        - name: pusher
          image: ${GUARDIAN_PUSHER_AWS_IMAGE}
          imagePullPolicy: ${GUARDIAN_IMAGE_PULL_POLICY}
          env:
            - name: GUARDIAN_PUSHER_NAME
              value: "${GUARDIAN_AWS_PUSHER_NAME}"
            - name: GUARDIAN_ACCOUNT
              value: "${GUARDIAN_AWS_ACCOUNT}"
            - name: GUARDIAN_REGION
              value: "${GUARDIAN_AWS_REGION}"
            - name: GUARDIAN_ASSUME_ROLE_NAME
              value: "${GUARDIAN_AWS_ASSUME_ROLE_NAME}"
            - name: GUARDIAN_LB_IMAGE
              value: "${GUARDIAN_LB_IMAGE}"
            - name: GUARDIAN_MONOFS_ROUTER
              value: "${GUARDIAN_MONOFS_ROUTER}"
            - name: GUARDIAN_MONOFS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: guardian-secrets
                  key: monofs-token
            - name: GUARDIAN_MONOFS_USE_EXTERNAL_ADDRESSES
              value: "${GUARDIAN_MONOFS_USE_EXTERNAL_ADDRESSES}"
