apiVersion: v1
kind: Service
metadata:
  name: guardian-ui-external
  namespace: ${NAMESPACE}
spec:
  type: ${EXTERNAL_SERVICE_TYPE}
  selector:
    app: guardiand
  ports:
    - name: http
      port: 8080
      targetPort: 8080
