// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: pkg/pb/discovery.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterServiceRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Account               string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	ServiceName           string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	TargetIp              string                 `protobuf:"bytes,3,opt,name=target_ip,json=targetIp,proto3" json:"target_ip,omitempty"`
	TargetPort            int32                  `protobuf:"varint,4,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`
	RequestedExternalPort int32                  `protobuf:"varint,5,opt,name=requested_external_port,json=requestedExternalPort,proto3" json:"requested_external_port,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RegisterServiceRequest) Reset() {
	*x = RegisterServiceRequest{}
	mi := &file_pkg_pb_discovery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterServiceRequest) ProtoMessage() {}

func (x *RegisterServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_discovery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterServiceRequest.ProtoReflect.Descriptor instead.
func (*RegisterServiceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_discovery_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterServiceRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *RegisterServiceRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *RegisterServiceRequest) GetTargetIp() string {
	if x != nil {
		return x.TargetIp
	}
	return ""
}

func (x *RegisterServiceRequest) GetTargetPort() int32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

func (x *RegisterServiceRequest) GetRequestedExternalPort() int32 {
	if x != nil {
		return x.RequestedExternalPort
	}
	return 0
}

type RegisterServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalPort  int32                  `protobuf:"varint,1,opt,name=external_port,json=externalPort,proto3" json:"external_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterServiceResponse) Reset() {
	*x = RegisterServiceResponse{}
	mi := &file_pkg_pb_discovery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterServiceResponse) ProtoMessage() {}

func (x *RegisterServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_discovery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterServiceResponse.ProtoReflect.Descriptor instead.
func (*RegisterServiceResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_discovery_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterServiceResponse) GetExternalPort() int32 {
	if x != nil {
		return x.ExternalPort
	}
	return 0
}

type DeregisterServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	TargetIp      string                 `protobuf:"bytes,3,opt,name=target_ip,json=targetIp,proto3" json:"target_ip,omitempty"`
	TargetPort    int32                  `protobuf:"varint,4,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterServiceRequest) Reset() {
	*x = DeregisterServiceRequest{}
	mi := &file_pkg_pb_discovery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterServiceRequest) ProtoMessage() {}

func (x *DeregisterServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_discovery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterServiceRequest.ProtoReflect.Descriptor instead.
func (*DeregisterServiceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_discovery_proto_rawDescGZIP(), []int{2}
}

func (x *DeregisterServiceRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *DeregisterServiceRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *DeregisterServiceRequest) GetTargetIp() string {
	if x != nil {
		return x.TargetIp
	}
	return ""
}

func (x *DeregisterServiceRequest) GetTargetPort() int32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

type DeregisterServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Removed       bool                   `protobuf:"varint,1,opt,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterServiceResponse) Reset() {
	*x = DeregisterServiceResponse{}
	mi := &file_pkg_pb_discovery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterServiceResponse) ProtoMessage() {}

func (x *DeregisterServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_discovery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterServiceResponse.ProtoReflect.Descriptor instead.
func (*DeregisterServiceResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_discovery_proto_rawDescGZIP(), []int{3}
}

func (x *DeregisterServiceResponse) GetRemoved() bool {
	if x != nil {
		return x.Removed
	}
	return false
}

type ListServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesRequest) Reset() {
	*x = ListServicesRequest{}
	mi := &file_pkg_pb_discovery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesRequest) ProtoMessage() {}

func (x *ListServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_discovery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesRequest.ProtoReflect.Descriptor instead.
func (*ListServicesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_discovery_proto_rawDescGZIP(), []int{4}
}

type Backend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetIp      string                 `protobuf:"bytes,1,opt,name=target_ip,json=targetIp,proto3" json:"target_ip,omitempty"`
	TargetPort    int32                  `protobuf:"varint,2,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Backend) Reset() {
	*x = Backend{}
	mi := &file_pkg_pb_discovery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Backend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Backend) ProtoMessage() {}

func (x *Backend) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_discovery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Backend.ProtoReflect.Descriptor instead.
func (*Backend) Descriptor() ([]byte, []int) {
	return file_pkg_pb_discovery_proto_rawDescGZIP(), []int{5}
}

func (x *Backend) GetTargetIp() string {
	if x != nil {
		return x.TargetIp
	}
	return ""
}

func (x *Backend) GetTargetPort() int32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

type ServiceRoute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ExternalPort  int32                  `protobuf:"varint,3,opt,name=external_port,json=externalPort,proto3" json:"external_port,omitempty"`
	Backends      []*Backend             `protobuf:"bytes,4,rep,name=backends,proto3" json:"backends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceRoute) Reset() {
	*x = ServiceRoute{}
	mi := &file_pkg_pb_discovery_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRoute) ProtoMessage() {}

func (x *ServiceRoute) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_discovery_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRoute.ProtoReflect.Descriptor instead.
func (*ServiceRoute) Descriptor() ([]byte, []int) {
	return file_pkg_pb_discovery_proto_rawDescGZIP(), []int{6}
}

func (x *ServiceRoute) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *ServiceRoute) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceRoute) GetExternalPort() int32 {
	if x != nil {
		return x.ExternalPort
	}
	return 0
}

func (x *ServiceRoute) GetBackends() []*Backend {
	if x != nil {
		return x.Backends
	}
	return nil
}

type ListServicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*ServiceRoute        `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesResponse) Reset() {
	*x = ListServicesResponse{}
	mi := &file_pkg_pb_discovery_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesResponse) ProtoMessage() {}

func (x *ListServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_discovery_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesResponse.ProtoReflect.Descriptor instead.
func (*ListServicesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_discovery_proto_rawDescGZIP(), []int{7}
}

func (x *ListServicesResponse) GetServices() []*ServiceRoute {
	if x != nil {
		return x.Services
	}
	return nil
}

var File_pkg_pb_discovery_proto protoreflect.FileDescriptor

const file_pkg_pb_discovery_proto_rawDesc = "" +
	"\n" +
	"\x16pkg/pb/discovery.proto\x12\x05lb.v1\"\xcb\x01\n" +
	"\x16RegisterServiceRequest\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x1b\n" +
	"\ttarget_ip\x18\x03 \x01(\tR\btargetIp\x12\x1f\n" +
	"\vtarget_port\x18\x04 \x01(\x05R\n" +
	"targetPort\x126\n" +
	"\x17requested_external_port\x18\x05 \x01(\x05R\x15requestedExternalPort\">\n" +
	"\x17RegisterServiceResponse\x12#\n" +
	"\rexternal_port\x18\x01 \x01(\x05R\fexternalPort\"\x95\x01\n" +
	"\x18DeregisterServiceRequest\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x1b\n" +
	"\ttarget_ip\x18\x03 \x01(\tR\btargetIp\x12\x1f\n" +
	"\vtarget_port\x18\x04 \x01(\x05R\n" +
	"targetPort\"5\n" +
	"\x19DeregisterServiceResponse\x12\x18\n" +
	"\aremoved\x18\x01 \x01(\bR\aremoved\"\x15\n" +
	"\x13ListServicesRequest\"G\n" +
	"\aBackend\x12\x1b\n" +
	"\ttarget_ip\x18\x01 \x01(\tR\btargetIp\x12\x1f\n" +
	"\vtarget_port\x18\x02 \x01(\x05R\n" +
	"targetPort\"\x9c\x01\n" +
	"\fServiceRoute\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12#\n" +
	"\rexternal_port\x18\x03 \x01(\x05R\fexternalPort\x12*\n" +
	"\bbackends\x18\x04 \x03(\v2\x0e.lb.v1.BackendR\bbackends\"G\n" +
	"\x14ListServicesResponse\x12/\n" +
	"\bservices\x18\x01 \x03(\v2\x13.lb.v1.ServiceRouteR\bservices2\x86\x02\n" +
	"\x11DiscoveryRegistry\x12P\n" +
	"\x0fRegisterService\x12\x1d.lb.v1.RegisterServiceRequest\x1a\x1e.lb.v1.RegisterServiceResponse\x12V\n" +
	"\x11DeregisterService\x12\x1f.lb.v1.DeregisterServiceRequest\x1a .lb.v1.DeregisterServiceResponse\x12G\n" +
	"\fListServices\x12\x1a.lb.v1.ListServicesRequest\x1a\x1b.lb.v1.ListServicesResponseB&Z$github.com/rydzu/ainfra/lb/pkg/pb;pbb\x06proto3"

var (
	file_pkg_pb_discovery_proto_rawDescOnce sync.Once
	file_pkg_pb_discovery_proto_rawDescData []byte
)

func file_pkg_pb_discovery_proto_rawDescGZIP() []byte {
	file_pkg_pb_discovery_proto_rawDescOnce.Do(func() {
		file_pkg_pb_discovery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_pb_discovery_proto_rawDesc), len(file_pkg_pb_discovery_proto_rawDesc)))
	})
	return file_pkg_pb_discovery_proto_rawDescData
}

var file_pkg_pb_discovery_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pkg_pb_discovery_proto_goTypes = []any{
	(*RegisterServiceRequest)(nil),    // 0: lb.v1.RegisterServiceRequest
	(*RegisterServiceResponse)(nil),   // 1: lb.v1.RegisterServiceResponse
	(*DeregisterServiceRequest)(nil),  // 2: lb.v1.DeregisterServiceRequest
	(*DeregisterServiceResponse)(nil), // 3: lb.v1.DeregisterServiceResponse
	(*ListServicesRequest)(nil),       // 4: lb.v1.ListServicesRequest
	(*Backend)(nil),                   // 5: lb.v1.Backend
	(*ServiceRoute)(nil),              // 6: lb.v1.ServiceRoute
	(*ListServicesResponse)(nil),      // 7: lb.v1.ListServicesResponse
}
var file_pkg_pb_discovery_proto_depIdxs = []int32{
	5, // 0: lb.v1.ServiceRoute.backends:type_name -> lb.v1.Backend
	6, // 1: lb.v1.ListServicesResponse.services:type_name -> lb.v1.ServiceRoute
	0, // 2: lb.v1.DiscoveryRegistry.RegisterService:input_type -> lb.v1.RegisterServiceRequest
	2, // 3: lb.v1.DiscoveryRegistry.DeregisterService:input_type -> lb.v1.DeregisterServiceRequest
	4, // 4: lb.v1.DiscoveryRegistry.ListServices:input_type -> lb.v1.ListServicesRequest
	1, // 5: lb.v1.DiscoveryRegistry.RegisterService:output_type -> lb.v1.RegisterServiceResponse
	3, // 6: lb.v1.DiscoveryRegistry.DeregisterService:output_type -> lb.v1.DeregisterServiceResponse
	7, // 7: lb.v1.DiscoveryRegistry.ListServices:output_type -> lb.v1.ListServicesResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_pb_discovery_proto_init() }
func file_pkg_pb_discovery_proto_init() {
	if File_pkg_pb_discovery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_pb_discovery_proto_rawDesc), len(file_pkg_pb_discovery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pb_discovery_proto_goTypes,
		DependencyIndexes: file_pkg_pb_discovery_proto_depIdxs,
		MessageInfos:      file_pkg_pb_discovery_proto_msgTypes,
	}.Build()
	File_pkg_pb_discovery_proto = out.File
	file_pkg_pb_discovery_proto_goTypes = nil
	file_pkg_pb_discovery_proto_depIdxs = nil
}
