apiVersion: guardian/v1alpha1
kind: Intent
metadata:
    name: lb-agent
spec:
    intentType: standard
    joins:
        - images
    targetPusher: k8s-main
    target:
        cluster: k8s-main
        namespace: lb-edge
    locked: false
    assets:
        - type: Compute
          name: lb-k8s-agent
          version: 20260624-1558
          payload:
            k8s: /partitions/lb-agent/payloads/k8s-agent.k8s.yaml
          properties:
            image: ${intent.images.outputs.lb-build.imageRef}
            imagePullPolicy: IfNotPresent
            resources:
                limits:
                    cpu: 200m
                    memory: 128Mi
                requests:
                    cpu: 50m
                    memory: 64Mi
