// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.31.1
// source: api/proto/fetcher.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BlobFetcher_FetchBlob_FullMethodName            = "/monofs.BlobFetcher/FetchBlob"
	BlobFetcher_FetchBlobBatch_FullMethodName       = "/monofs.BlobFetcher/FetchBlobBatch"
	BlobFetcher_PrefetchBlobs_FullMethodName        = "/monofs.BlobFetcher/PrefetchBlobs"
	BlobFetcher_CheckCache_FullMethodName           = "/monofs.BlobFetcher/CheckCache"
	BlobFetcher_GetStats_FullMethodName             = "/monofs.BlobFetcher/GetStats"
	BlobFetcher_StoreBlob_FullMethodName            = "/monofs.BlobFetcher/StoreBlob"
	BlobFetcher_StoreBlobBatchStream_FullMethodName = "/monofs.BlobFetcher/StoreBlobBatchStream"
	BlobFetcher_DeleteBlobs_FullMethodName          = "/monofs.BlobFetcher/DeleteBlobs"
	BlobFetcher_StoreArchive_FullMethodName         = "/monofs.BlobFetcher/StoreArchive"
)

// BlobFetcherClient is the client API for BlobFetcher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BlobFetcher service - stateless proxies for external data sources.
// Runs in DMZ with external network access. Storage nodes call this
// to fetch blobs without needing direct external connectivity.
type BlobFetcherClient interface {
	// Synchronous fetch - blocks until blob is returned or error.
	// Used for cache misses that need immediate data.
	FetchBlob(ctx context.Context, in *FetchBlobRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataChunk], error)
	// Batch fetch - parallel retrieval of multiple blobs.
	// Used for bulk prefetch operations.
	FetchBlobBatch(ctx context.Context, in *FetchBlobBatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FetchBlobBatchResponse], error)
	// Async prefetch - best-effort background fetch.
	// Returns immediately, blobs fetched in background.
	// Caller should poll or re-request via FetchBlob.
	PrefetchBlobs(ctx context.Context, in *PrefetchRequest, opts ...grpc.CallOption) (*PrefetchResponse, error)
	// Check if blobs are ready (cached on fetcher).
	CheckCache(ctx context.Context, in *CheckCacheRequest, opts ...grpc.CallOption) (*CheckCacheResponse, error)
	// Service health and statistics.
	GetStats(ctx context.Context, in *FetcherStatsRequest, opts ...grpc.CallOption) (*FetcherStatsResponse, error)
	// Store a single blob on the fetcher.
	// Called by storage nodes during ingestion.
	StoreBlob(ctx context.Context, in *StoreBlobRequest, opts ...grpc.CallOption) (*StoreBlobResponse, error)
	// Store multiple blobs as packed archives via client-streaming.
	// The client streams StoreBlobEntry messages; the fetcher packs them
	// into archive(s) splitting at ~512 MB. This avoids thousands of
	// individual loose files and supports arbitrarily large pushes.
	StoreBlobBatchStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StoreBlobEntry, StoreBlobBatchResponse], error)
	// Delete blobs from the fetcher's index and optionally clean up
	// archives that become empty.
	DeleteBlobs(ctx context.Context, in *DeleteBlobsRequest, opts ...grpc.CallOption) (*DeleteBlobsResponse, error)
	// Store a packager archive on the fetcher.
	// Called by the router during ingestion to push pre-built archives.
	StoreArchive(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StoreArchiveChunk, StoreArchiveResponse], error)
}

type blobFetcherClient struct {
	cc grpc.ClientConnInterface
}

func NewBlobFetcherClient(cc grpc.ClientConnInterface) BlobFetcherClient {
	return &blobFetcherClient{cc}
}

func (c *blobFetcherClient) FetchBlob(ctx context.Context, in *FetchBlobRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BlobFetcher_ServiceDesc.Streams[0], BlobFetcher_FetchBlob_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FetchBlobRequest, DataChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlobFetcher_FetchBlobClient = grpc.ServerStreamingClient[DataChunk]

func (c *blobFetcherClient) FetchBlobBatch(ctx context.Context, in *FetchBlobBatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FetchBlobBatchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BlobFetcher_ServiceDesc.Streams[1], BlobFetcher_FetchBlobBatch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FetchBlobBatchRequest, FetchBlobBatchResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlobFetcher_FetchBlobBatchClient = grpc.ServerStreamingClient[FetchBlobBatchResponse]

func (c *blobFetcherClient) PrefetchBlobs(ctx context.Context, in *PrefetchRequest, opts ...grpc.CallOption) (*PrefetchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrefetchResponse)
	err := c.cc.Invoke(ctx, BlobFetcher_PrefetchBlobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blobFetcherClient) CheckCache(ctx context.Context, in *CheckCacheRequest, opts ...grpc.CallOption) (*CheckCacheResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckCacheResponse)
	err := c.cc.Invoke(ctx, BlobFetcher_CheckCache_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blobFetcherClient) GetStats(ctx context.Context, in *FetcherStatsRequest, opts ...grpc.CallOption) (*FetcherStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetcherStatsResponse)
	err := c.cc.Invoke(ctx, BlobFetcher_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blobFetcherClient) StoreBlob(ctx context.Context, in *StoreBlobRequest, opts ...grpc.CallOption) (*StoreBlobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreBlobResponse)
	err := c.cc.Invoke(ctx, BlobFetcher_StoreBlob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blobFetcherClient) StoreBlobBatchStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StoreBlobEntry, StoreBlobBatchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BlobFetcher_ServiceDesc.Streams[2], BlobFetcher_StoreBlobBatchStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StoreBlobEntry, StoreBlobBatchResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlobFetcher_StoreBlobBatchStreamClient = grpc.ClientStreamingClient[StoreBlobEntry, StoreBlobBatchResponse]

func (c *blobFetcherClient) DeleteBlobs(ctx context.Context, in *DeleteBlobsRequest, opts ...grpc.CallOption) (*DeleteBlobsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBlobsResponse)
	err := c.cc.Invoke(ctx, BlobFetcher_DeleteBlobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blobFetcherClient) StoreArchive(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StoreArchiveChunk, StoreArchiveResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BlobFetcher_ServiceDesc.Streams[3], BlobFetcher_StoreArchive_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StoreArchiveChunk, StoreArchiveResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlobFetcher_StoreArchiveClient = grpc.ClientStreamingClient[StoreArchiveChunk, StoreArchiveResponse]

// BlobFetcherServer is the server API for BlobFetcher service.
// All implementations must embed UnimplementedBlobFetcherServer
// for forward compatibility.
//
// BlobFetcher service - stateless proxies for external data sources.
// Runs in DMZ with external network access. Storage nodes call this
// to fetch blobs without needing direct external connectivity.
type BlobFetcherServer interface {
	// Synchronous fetch - blocks until blob is returned or error.
	// Used for cache misses that need immediate data.
	FetchBlob(*FetchBlobRequest, grpc.ServerStreamingServer[DataChunk]) error
	// Batch fetch - parallel retrieval of multiple blobs.
	// Used for bulk prefetch operations.
	FetchBlobBatch(*FetchBlobBatchRequest, grpc.ServerStreamingServer[FetchBlobBatchResponse]) error
	// Async prefetch - best-effort background fetch.
	// Returns immediately, blobs fetched in background.
	// Caller should poll or re-request via FetchBlob.
	PrefetchBlobs(context.Context, *PrefetchRequest) (*PrefetchResponse, error)
	// Check if blobs are ready (cached on fetcher).
	CheckCache(context.Context, *CheckCacheRequest) (*CheckCacheResponse, error)
	// Service health and statistics.
	GetStats(context.Context, *FetcherStatsRequest) (*FetcherStatsResponse, error)
	// Store a single blob on the fetcher.
	// Called by storage nodes during ingestion.
	StoreBlob(context.Context, *StoreBlobRequest) (*StoreBlobResponse, error)
	// Store multiple blobs as packed archives via client-streaming.
	// The client streams StoreBlobEntry messages; the fetcher packs them
	// into archive(s) splitting at ~512 MB. This avoids thousands of
	// individual loose files and supports arbitrarily large pushes.
	StoreBlobBatchStream(grpc.ClientStreamingServer[StoreBlobEntry, StoreBlobBatchResponse]) error
	// Delete blobs from the fetcher's index and optionally clean up
	// archives that become empty.
	DeleteBlobs(context.Context, *DeleteBlobsRequest) (*DeleteBlobsResponse, error)
	// Store a packager archive on the fetcher.
	// Called by the router during ingestion to push pre-built archives.
	StoreArchive(grpc.ClientStreamingServer[StoreArchiveChunk, StoreArchiveResponse]) error
	mustEmbedUnimplementedBlobFetcherServer()
}

// UnimplementedBlobFetcherServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlobFetcherServer struct{}

func (UnimplementedBlobFetcherServer) FetchBlob(*FetchBlobRequest, grpc.ServerStreamingServer[DataChunk]) error {
	return status.Error(codes.Unimplemented, "method FetchBlob not implemented")
}
func (UnimplementedBlobFetcherServer) FetchBlobBatch(*FetchBlobBatchRequest, grpc.ServerStreamingServer[FetchBlobBatchResponse]) error {
	return status.Error(codes.Unimplemented, "method FetchBlobBatch not implemented")
}
func (UnimplementedBlobFetcherServer) PrefetchBlobs(context.Context, *PrefetchRequest) (*PrefetchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PrefetchBlobs not implemented")
}
func (UnimplementedBlobFetcherServer) CheckCache(context.Context, *CheckCacheRequest) (*CheckCacheResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckCache not implemented")
}
func (UnimplementedBlobFetcherServer) GetStats(context.Context, *FetcherStatsRequest) (*FetcherStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedBlobFetcherServer) StoreBlob(context.Context, *StoreBlobRequest) (*StoreBlobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StoreBlob not implemented")
}
func (UnimplementedBlobFetcherServer) StoreBlobBatchStream(grpc.ClientStreamingServer[StoreBlobEntry, StoreBlobBatchResponse]) error {
	return status.Error(codes.Unimplemented, "method StoreBlobBatchStream not implemented")
}
func (UnimplementedBlobFetcherServer) DeleteBlobs(context.Context, *DeleteBlobsRequest) (*DeleteBlobsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBlobs not implemented")
}
func (UnimplementedBlobFetcherServer) StoreArchive(grpc.ClientStreamingServer[StoreArchiveChunk, StoreArchiveResponse]) error {
	return status.Error(codes.Unimplemented, "method StoreArchive not implemented")
}
func (UnimplementedBlobFetcherServer) mustEmbedUnimplementedBlobFetcherServer() {}
func (UnimplementedBlobFetcherServer) testEmbeddedByValue()                     {}

// UnsafeBlobFetcherServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlobFetcherServer will
// result in compilation errors.
type UnsafeBlobFetcherServer interface {
	mustEmbedUnimplementedBlobFetcherServer()
}

func RegisterBlobFetcherServer(s grpc.ServiceRegistrar, srv BlobFetcherServer) {
	// If the following call panics, it indicates UnimplementedBlobFetcherServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BlobFetcher_ServiceDesc, srv)
}

func _BlobFetcher_FetchBlob_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FetchBlobRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BlobFetcherServer).FetchBlob(m, &grpc.GenericServerStream[FetchBlobRequest, DataChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlobFetcher_FetchBlobServer = grpc.ServerStreamingServer[DataChunk]

func _BlobFetcher_FetchBlobBatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FetchBlobBatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BlobFetcherServer).FetchBlobBatch(m, &grpc.GenericServerStream[FetchBlobBatchRequest, FetchBlobBatchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlobFetcher_FetchBlobBatchServer = grpc.ServerStreamingServer[FetchBlobBatchResponse]

func _BlobFetcher_PrefetchBlobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrefetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlobFetcherServer).PrefetchBlobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlobFetcher_PrefetchBlobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlobFetcherServer).PrefetchBlobs(ctx, req.(*PrefetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlobFetcher_CheckCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckCacheRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlobFetcherServer).CheckCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlobFetcher_CheckCache_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlobFetcherServer).CheckCache(ctx, req.(*CheckCacheRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlobFetcher_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetcherStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlobFetcherServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlobFetcher_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlobFetcherServer).GetStats(ctx, req.(*FetcherStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlobFetcher_StoreBlob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreBlobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlobFetcherServer).StoreBlob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlobFetcher_StoreBlob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlobFetcherServer).StoreBlob(ctx, req.(*StoreBlobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlobFetcher_StoreBlobBatchStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BlobFetcherServer).StoreBlobBatchStream(&grpc.GenericServerStream[StoreBlobEntry, StoreBlobBatchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlobFetcher_StoreBlobBatchStreamServer = grpc.ClientStreamingServer[StoreBlobEntry, StoreBlobBatchResponse]

func _BlobFetcher_DeleteBlobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBlobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlobFetcherServer).DeleteBlobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlobFetcher_DeleteBlobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlobFetcherServer).DeleteBlobs(ctx, req.(*DeleteBlobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlobFetcher_StoreArchive_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BlobFetcherServer).StoreArchive(&grpc.GenericServerStream[StoreArchiveChunk, StoreArchiveResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlobFetcher_StoreArchiveServer = grpc.ClientStreamingServer[StoreArchiveChunk, StoreArchiveResponse]

// BlobFetcher_ServiceDesc is the grpc.ServiceDesc for BlobFetcher service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlobFetcher_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "monofs.BlobFetcher",
	HandlerType: (*BlobFetcherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PrefetchBlobs",
			Handler:    _BlobFetcher_PrefetchBlobs_Handler,
		},
		{
			MethodName: "CheckCache",
			Handler:    _BlobFetcher_CheckCache_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _BlobFetcher_GetStats_Handler,
		},
		{
			MethodName: "StoreBlob",
			Handler:    _BlobFetcher_StoreBlob_Handler,
		},
		{
			MethodName: "DeleteBlobs",
			Handler:    _BlobFetcher_DeleteBlobs_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FetchBlob",
			Handler:       _BlobFetcher_FetchBlob_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "FetchBlobBatch",
			Handler:       _BlobFetcher_FetchBlobBatch_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StoreBlobBatchStream",
			Handler:       _BlobFetcher_StoreBlobBatchStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StoreArchive",
			Handler:       _BlobFetcher_StoreArchive_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/fetcher.proto",
}

const (
	RepoSyncWorker_StageWorkspaceBundle_FullMethodName       = "/monofs.RepoSyncWorker/StageWorkspaceBundle"
	RepoSyncWorker_StageWorkspaceCommitBundle_FullMethodName = "/monofs.RepoSyncWorker/StageWorkspaceCommitBundle"
	RepoSyncWorker_StartWorkspacePublish_FullMethodName      = "/monofs.RepoSyncWorker/StartWorkspacePublish"
	RepoSyncWorker_StartWorkspaceCommitPush_FullMethodName   = "/monofs.RepoSyncWorker/StartWorkspaceCommitPush"
	RepoSyncWorker_ProbeWorkspaceRefresh_FullMethodName      = "/monofs.RepoSyncWorker/ProbeWorkspaceRefresh"
	RepoSyncWorker_DiscardWorkspaceBundle_FullMethodName     = "/monofs.RepoSyncWorker/DiscardWorkspaceBundle"
	RepoSyncWorker_GetSyncWorkerStats_FullMethodName         = "/monofs.RepoSyncWorker/GetSyncWorkerStats"
)

// RepoSyncWorkerClient is the client API for RepoSyncWorker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RepoSyncWorker performs remote Git sync operations in the DMZ tier.
// Router orchestrates jobs; the worker talks to upstream repositories.
type RepoSyncWorkerClient interface {
	StageWorkspaceBundle(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WorkspaceBundleChunk, StageWorkspaceBundleResponse], error)
	StageWorkspaceCommitBundle(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WorkspaceBundleChunk, StageWorkspaceBundleResponse], error)
	StartWorkspacePublish(ctx context.Context, in *StartWorkspacePublishRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RepoSyncProgress], error)
	StartWorkspaceCommitPush(ctx context.Context, in *StartWorkspaceCommitPushRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RepoSyncProgress], error)
	ProbeWorkspaceRefresh(ctx context.Context, in *ProbeWorkspaceRefreshRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RepoSyncProgress], error)
	DiscardWorkspaceBundle(ctx context.Context, in *DiscardWorkspaceBundleRequest, opts ...grpc.CallOption) (*DiscardWorkspaceBundleResponse, error)
	GetSyncWorkerStats(ctx context.Context, in *SyncWorkerStatsRequest, opts ...grpc.CallOption) (*SyncWorkerStatsResponse, error)
}

type repoSyncWorkerClient struct {
	cc grpc.ClientConnInterface
}

func NewRepoSyncWorkerClient(cc grpc.ClientConnInterface) RepoSyncWorkerClient {
	return &repoSyncWorkerClient{cc}
}

func (c *repoSyncWorkerClient) StageWorkspaceBundle(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WorkspaceBundleChunk, StageWorkspaceBundleResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RepoSyncWorker_ServiceDesc.Streams[0], RepoSyncWorker_StageWorkspaceBundle_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WorkspaceBundleChunk, StageWorkspaceBundleResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RepoSyncWorker_StageWorkspaceBundleClient = grpc.ClientStreamingClient[WorkspaceBundleChunk, StageWorkspaceBundleResponse]

func (c *repoSyncWorkerClient) StageWorkspaceCommitBundle(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WorkspaceBundleChunk, StageWorkspaceBundleResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RepoSyncWorker_ServiceDesc.Streams[1], RepoSyncWorker_StageWorkspaceCommitBundle_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WorkspaceBundleChunk, StageWorkspaceBundleResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RepoSyncWorker_StageWorkspaceCommitBundleClient = grpc.ClientStreamingClient[WorkspaceBundleChunk, StageWorkspaceBundleResponse]

func (c *repoSyncWorkerClient) StartWorkspacePublish(ctx context.Context, in *StartWorkspacePublishRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RepoSyncProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RepoSyncWorker_ServiceDesc.Streams[2], RepoSyncWorker_StartWorkspacePublish_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StartWorkspacePublishRequest, RepoSyncProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RepoSyncWorker_StartWorkspacePublishClient = grpc.ServerStreamingClient[RepoSyncProgress]

func (c *repoSyncWorkerClient) StartWorkspaceCommitPush(ctx context.Context, in *StartWorkspaceCommitPushRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RepoSyncProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RepoSyncWorker_ServiceDesc.Streams[3], RepoSyncWorker_StartWorkspaceCommitPush_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StartWorkspaceCommitPushRequest, RepoSyncProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RepoSyncWorker_StartWorkspaceCommitPushClient = grpc.ServerStreamingClient[RepoSyncProgress]

func (c *repoSyncWorkerClient) ProbeWorkspaceRefresh(ctx context.Context, in *ProbeWorkspaceRefreshRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RepoSyncProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RepoSyncWorker_ServiceDesc.Streams[4], RepoSyncWorker_ProbeWorkspaceRefresh_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProbeWorkspaceRefreshRequest, RepoSyncProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RepoSyncWorker_ProbeWorkspaceRefreshClient = grpc.ServerStreamingClient[RepoSyncProgress]

func (c *repoSyncWorkerClient) DiscardWorkspaceBundle(ctx context.Context, in *DiscardWorkspaceBundleRequest, opts ...grpc.CallOption) (*DiscardWorkspaceBundleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscardWorkspaceBundleResponse)
	err := c.cc.Invoke(ctx, RepoSyncWorker_DiscardWorkspaceBundle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repoSyncWorkerClient) GetSyncWorkerStats(ctx context.Context, in *SyncWorkerStatsRequest, opts ...grpc.CallOption) (*SyncWorkerStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncWorkerStatsResponse)
	err := c.cc.Invoke(ctx, RepoSyncWorker_GetSyncWorkerStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RepoSyncWorkerServer is the server API for RepoSyncWorker service.
// All implementations must embed UnimplementedRepoSyncWorkerServer
// for forward compatibility.
//
// RepoSyncWorker performs remote Git sync operations in the DMZ tier.
// Router orchestrates jobs; the worker talks to upstream repositories.
type RepoSyncWorkerServer interface {
	StageWorkspaceBundle(grpc.ClientStreamingServer[WorkspaceBundleChunk, StageWorkspaceBundleResponse]) error
	StageWorkspaceCommitBundle(grpc.ClientStreamingServer[WorkspaceBundleChunk, StageWorkspaceBundleResponse]) error
	StartWorkspacePublish(*StartWorkspacePublishRequest, grpc.ServerStreamingServer[RepoSyncProgress]) error
	StartWorkspaceCommitPush(*StartWorkspaceCommitPushRequest, grpc.ServerStreamingServer[RepoSyncProgress]) error
	ProbeWorkspaceRefresh(*ProbeWorkspaceRefreshRequest, grpc.ServerStreamingServer[RepoSyncProgress]) error
	DiscardWorkspaceBundle(context.Context, *DiscardWorkspaceBundleRequest) (*DiscardWorkspaceBundleResponse, error)
	GetSyncWorkerStats(context.Context, *SyncWorkerStatsRequest) (*SyncWorkerStatsResponse, error)
	mustEmbedUnimplementedRepoSyncWorkerServer()
}

// UnimplementedRepoSyncWorkerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRepoSyncWorkerServer struct{}

func (UnimplementedRepoSyncWorkerServer) StageWorkspaceBundle(grpc.ClientStreamingServer[WorkspaceBundleChunk, StageWorkspaceBundleResponse]) error {
	return status.Error(codes.Unimplemented, "method StageWorkspaceBundle not implemented")
}
func (UnimplementedRepoSyncWorkerServer) StageWorkspaceCommitBundle(grpc.ClientStreamingServer[WorkspaceBundleChunk, StageWorkspaceBundleResponse]) error {
	return status.Error(codes.Unimplemented, "method StageWorkspaceCommitBundle not implemented")
}
func (UnimplementedRepoSyncWorkerServer) StartWorkspacePublish(*StartWorkspacePublishRequest, grpc.ServerStreamingServer[RepoSyncProgress]) error {
	return status.Error(codes.Unimplemented, "method StartWorkspacePublish not implemented")
}
func (UnimplementedRepoSyncWorkerServer) StartWorkspaceCommitPush(*StartWorkspaceCommitPushRequest, grpc.ServerStreamingServer[RepoSyncProgress]) error {
	return status.Error(codes.Unimplemented, "method StartWorkspaceCommitPush not implemented")
}
func (UnimplementedRepoSyncWorkerServer) ProbeWorkspaceRefresh(*ProbeWorkspaceRefreshRequest, grpc.ServerStreamingServer[RepoSyncProgress]) error {
	return status.Error(codes.Unimplemented, "method ProbeWorkspaceRefresh not implemented")
}
func (UnimplementedRepoSyncWorkerServer) DiscardWorkspaceBundle(context.Context, *DiscardWorkspaceBundleRequest) (*DiscardWorkspaceBundleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DiscardWorkspaceBundle not implemented")
}
func (UnimplementedRepoSyncWorkerServer) GetSyncWorkerStats(context.Context, *SyncWorkerStatsRequest) (*SyncWorkerStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSyncWorkerStats not implemented")
}
func (UnimplementedRepoSyncWorkerServer) mustEmbedUnimplementedRepoSyncWorkerServer() {}
func (UnimplementedRepoSyncWorkerServer) testEmbeddedByValue()                        {}

// UnsafeRepoSyncWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RepoSyncWorkerServer will
// result in compilation errors.
type UnsafeRepoSyncWorkerServer interface {
	mustEmbedUnimplementedRepoSyncWorkerServer()
}

func RegisterRepoSyncWorkerServer(s grpc.ServiceRegistrar, srv RepoSyncWorkerServer) {
	// If the following call panics, it indicates UnimplementedRepoSyncWorkerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RepoSyncWorker_ServiceDesc, srv)
}

func _RepoSyncWorker_StageWorkspaceBundle_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RepoSyncWorkerServer).StageWorkspaceBundle(&grpc.GenericServerStream[WorkspaceBundleChunk, StageWorkspaceBundleResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RepoSyncWorker_StageWorkspaceBundleServer = grpc.ClientStreamingServer[WorkspaceBundleChunk, StageWorkspaceBundleResponse]

func _RepoSyncWorker_StageWorkspaceCommitBundle_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RepoSyncWorkerServer).StageWorkspaceCommitBundle(&grpc.GenericServerStream[WorkspaceBundleChunk, StageWorkspaceBundleResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RepoSyncWorker_StageWorkspaceCommitBundleServer = grpc.ClientStreamingServer[WorkspaceBundleChunk, StageWorkspaceBundleResponse]

func _RepoSyncWorker_StartWorkspacePublish_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StartWorkspacePublishRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RepoSyncWorkerServer).StartWorkspacePublish(m, &grpc.GenericServerStream[StartWorkspacePublishRequest, RepoSyncProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RepoSyncWorker_StartWorkspacePublishServer = grpc.ServerStreamingServer[RepoSyncProgress]

func _RepoSyncWorker_StartWorkspaceCommitPush_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StartWorkspaceCommitPushRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RepoSyncWorkerServer).StartWorkspaceCommitPush(m, &grpc.GenericServerStream[StartWorkspaceCommitPushRequest, RepoSyncProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RepoSyncWorker_StartWorkspaceCommitPushServer = grpc.ServerStreamingServer[RepoSyncProgress]

func _RepoSyncWorker_ProbeWorkspaceRefresh_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProbeWorkspaceRefreshRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RepoSyncWorkerServer).ProbeWorkspaceRefresh(m, &grpc.GenericServerStream[ProbeWorkspaceRefreshRequest, RepoSyncProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RepoSyncWorker_ProbeWorkspaceRefreshServer = grpc.ServerStreamingServer[RepoSyncProgress]

func _RepoSyncWorker_DiscardWorkspaceBundle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscardWorkspaceBundleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepoSyncWorkerServer).DiscardWorkspaceBundle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RepoSyncWorker_DiscardWorkspaceBundle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepoSyncWorkerServer).DiscardWorkspaceBundle(ctx, req.(*DiscardWorkspaceBundleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RepoSyncWorker_GetSyncWorkerStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncWorkerStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepoSyncWorkerServer).GetSyncWorkerStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RepoSyncWorker_GetSyncWorkerStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepoSyncWorkerServer).GetSyncWorkerStats(ctx, req.(*SyncWorkerStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RepoSyncWorker_ServiceDesc is the grpc.ServiceDesc for RepoSyncWorker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RepoSyncWorker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "monofs.RepoSyncWorker",
	HandlerType: (*RepoSyncWorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DiscardWorkspaceBundle",
			Handler:    _RepoSyncWorker_DiscardWorkspaceBundle_Handler,
		},
		{
			MethodName: "GetSyncWorkerStats",
			Handler:    _RepoSyncWorker_GetSyncWorkerStats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StageWorkspaceBundle",
			Handler:       _RepoSyncWorker_StageWorkspaceBundle_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StageWorkspaceCommitBundle",
			Handler:       _RepoSyncWorker_StageWorkspaceCommitBundle_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StartWorkspacePublish",
			Handler:       _RepoSyncWorker_StartWorkspacePublish_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StartWorkspaceCommitPush",
			Handler:       _RepoSyncWorker_StartWorkspaceCommitPush_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ProbeWorkspaceRefresh",
			Handler:       _RepoSyncWorker_ProbeWorkspaceRefresh_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/fetcher.proto",
}
