apiVersion: guardian/v1alpha1
kind: Partition
metadata:
  name: doctor
  labels:
    role: observability
spec:
  deletionPolicy: orphan
  reconciliation:
    mode: auto
    interval: 1m
  labels:
    stack: k8s
    component: doctor
    topology: kubernetes
    managedBy: guardian
    endpoint: http://k8s-svc-compute-k8s-main-doctor-doctor-query-query.doctor.svc.cluster.local:18080
