"""Shared MonoFS encryption-key helpers."""
from __future__ import annotations

from dataclasses import dataclass
import os
import re
import secrets
from pathlib import Path

from stratatools.util import ROOT

AINFRA = ROOT.parent
KEY_NAME = "MONOFS_ENCRYPTION_KEY"


@dataclass(frozen=True)
class MonofsEncryptionKeyState:
    key: str
    source: str | None
    env_file: Path
    created: bool = False


def monofs_repo_dir(repo_dir: Path | None = None) -> Path:
    if repo_dir is not None:
        return Path(repo_dir).expanduser()
    return Path(os.environ.get("MONOFS_REPO_DIR", str(AINFRA / "monofs"))).expanduser()


def monofs_env_file(repo_dir: Path | None = None) -> Path:
    return monofs_repo_dir(repo_dir) / ".env"


def read_dotenv_value(path: Path, key: str) -> str:
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        name, value = line.split("=", 1)
        if name.strip() != key:
            continue
        return value.strip().strip("\"'")
    return ""


def write_dotenv_value(path: Path, key: str, value: str) -> None:
    if path.is_file():
        lines = path.read_text(encoding="utf-8").splitlines()
    else:
        lines = [
            "# MonoFS Docker Compose Environment Variables",
            "#",
            "# Auto-generated by stratatools.",
            "",
        ]

    updated = False
    rendered: list[str] = []
    for line in lines:
        if line.strip().startswith(f"{key}="):
            rendered.append(f"{key}={value}")
            updated = True
            continue
        rendered.append(line)

    if not updated:
        if rendered and rendered[-1] != "":
            rendered.append("")
        rendered.append(f"{key}={value}")

    path.write_text("\n".join(rendered) + "\n", encoding="utf-8")


def generate_monofs_encryption_key() -> str:
    return secrets.token_hex(32)


def is_valid_monofs_encryption_key(value: str) -> bool:
    return bool(re.fullmatch(r"[0-9a-fA-F]{64}", value))


def resolve_monofs_encryption_key_state(
    *, repo_dir: Path | None = None
) -> MonofsEncryptionKeyState:
    env_file = monofs_env_file(repo_dir)
    env_value = os.environ.get(KEY_NAME, "").strip()
    file_value = ""
    if env_file.is_file():
        file_value = read_dotenv_value(env_file, KEY_NAME)

    if is_valid_monofs_encryption_key(file_value):
        return MonofsEncryptionKeyState(
            key=file_value,
            source=str(env_file),
            env_file=env_file,
        )
    if is_valid_monofs_encryption_key(env_value):
        return MonofsEncryptionKeyState(
            key=env_value,
            source=f"environment variable {KEY_NAME}",
            env_file=env_file,
        )
    if file_value:
        return MonofsEncryptionKeyState(
            key=file_value,
            source=str(env_file),
            env_file=env_file,
        )
    if env_value:
        return MonofsEncryptionKeyState(
            key=env_value,
            source=f"environment variable {KEY_NAME}",
            env_file=env_file,
        )
    return MonofsEncryptionKeyState(key="", source=None, env_file=env_file)


def ensure_monofs_encryption_key(
    *,
    repo_dir: Path | None = None,
    dry_run: bool = False,
    create_if_missing: bool = True,
) -> MonofsEncryptionKeyState:
    state = resolve_monofs_encryption_key_state(repo_dir=repo_dir)
    if is_valid_monofs_encryption_key(state.key):
        env_file = state.env_file
        os.environ[KEY_NAME] = state.key
        if state.source == str(env_file):
            return state

        if not dry_run:
            env_file.parent.mkdir(parents=True, exist_ok=True)
            write_dotenv_value(env_file, KEY_NAME, state.key)
        return MonofsEncryptionKeyState(
            key=state.key,
            source=state.source,
            env_file=env_file,
            created=True,
        )

    if state.key:
        source = state.source or KEY_NAME
        raise ValueError(
            f"{KEY_NAME} from {source} is invalid; expected 64 hex characters"
        )

    if not create_if_missing:
        raise FileNotFoundError(
            f"{KEY_NAME} is not configured; expected it in {state.env_file}"
        )

    repo_path = monofs_repo_dir(repo_dir)
    if not repo_path.is_dir() and not dry_run:
        raise FileNotFoundError(f"monofs repo not found: {repo_path}")

    key = generate_monofs_encryption_key()
    if not dry_run:
        env_file = monofs_env_file(repo_dir)
        env_file.parent.mkdir(parents=True, exist_ok=True)
        write_dotenv_value(env_file, KEY_NAME, key)
    os.environ[KEY_NAME] = key
    return MonofsEncryptionKeyState(
        key=key,
        source=state.source,
        env_file=monofs_env_file(repo_dir),
        created=True,
    )